/**
 * Data-driven template configuration system.
 * Each config defines a unique visual style rendered by ConfigurableTemplate.tsx
 */

export interface TemplateConfig {
  id: string;
  name: string;
  category: string;
  description: string;
  // Page background
  pageBg: string;
  // Header / hero area
  headerBg: string;
  headerHeight: string;
  headerImage?: string;         // background-image URL for header
  headerOverlay?: string;       // overlay gradient on top of image
  headerPattern?: string;       // CSS pattern overlay
  // Card area
  cardBg: string;
  cardBorder: string;
  cardShadow: string;
  cardRadius: string;
  cardBlur?: boolean;           // backdrop-blur
  // Profile
  profileShape: 'circle' | 'rounded' | 'square' | 'hexagon';
  profileBorder: string;
  profileShadow: string;
  profileSize: string;
  // Typography
  nameColor: string;
  titleColor: string;
  companyColor: string;
  labelColor: string;
  sectionTitleColor: string;
  fontClass: string;            // tailwind font class or google font
  // Action buttons
  actionStyle: 'filled' | 'outline' | 'glass' | 'soft' | 'gradient';
  actionColors: { call: string; email: string; whatsapp: string; save: string };
  // Social icons
  socialColor: string;
  socialHoverColor: string;
  // Services section
  serviceBg: string;
  serviceBorder: string;
  serviceIconBg: string;
  // Divider
  dividerStyle: string;
  // Footer
  footerColor: string;
  // Decorations (CSS-based)
  decorations?: {
    type: 'dots' | 'lines' | 'circles' | 'triangles' | 'waves' | 'none';
    color: string;
    opacity: number;
  };
}

// Helper to create consistent action color sets
const actions = {
  light: { call: 'bg-green-500 text-white', email: 'bg-blue-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-indigo-500 text-white' },
  dark: { call: 'bg-green-500/20 text-green-400 border border-green-500/30', email: 'bg-blue-500/20 text-blue-400 border border-blue-500/30', whatsapp: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30', save: 'bg-indigo-500/20 text-indigo-400 border border-indigo-500/30' },
  glass: { call: 'bg-white/10 text-white border border-white/20', email: 'bg-white/10 text-white border border-white/20', whatsapp: 'bg-white/10 text-white border border-white/20', save: 'bg-white/10 text-white border border-white/20' },
  warm: { call: 'bg-orange-500 text-white', email: 'bg-rose-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-amber-500 text-white' },
  cool: { call: 'bg-teal-500 text-white', email: 'bg-cyan-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-sky-500 text-white' },
  mono: { call: 'bg-gray-800 text-white', email: 'bg-gray-700 text-white', whatsapp: 'bg-gray-600 text-white', save: 'bg-gray-900 text-white' },
};

const UNSPLASH = 'https://images.unsplash.com';

export const templateConfigs: TemplateConfig[] = [
  // ═══════════════════════════════════════════════
  // CATEGORY: BACKGROUND IMAGE HEADERS (11-25)
  // ═══════════════════════════════════════════════
  {
    id: 'city-skyline',
    name: 'City Skyline',
    category: 'Photo Header',
    description: 'Aerial city view with glass card overlay',
    pageBg: '#f0f2f5',
    headerBg: '#1a1a2e',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1477959858617-67f85cf4f1df?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.6) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-gray-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-xl',
    profileSize: 'w-28 h-28',
    nameColor: 'text-gray-900',
    titleColor: 'text-gray-500',
    companyColor: 'text-indigo-600',
    labelColor: 'text-gray-400',
    sectionTitleColor: 'text-indigo-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.light,
    socialColor: 'text-gray-400',
    socialHoverColor: 'hover:text-gray-700',
    serviceBg: 'bg-gray-50',
    serviceBorder: 'border-gray-100',
    serviceIconBg: 'bg-indigo-100 text-indigo-600',
    dividerStyle: 'h-px bg-gray-200',
    footerColor: 'text-gray-300',
  },
  {
    id: 'mountain-peak',
    name: 'Mountain Peak',
    category: 'Photo Header',
    description: 'Majestic mountain backdrop with warm tones',
    pageBg: '#faf8f5',
    headerBg: '#2d3436',
    headerHeight: 'h-60',
    headerImage: `${UNSPLASH}/photo-1506905925346-21bda4d32df4?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(45,52,54,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-stone-900',
    titleColor: 'text-stone-500',
    companyColor: 'text-amber-700',
    labelColor: 'text-stone-400',
    sectionTitleColor: 'text-amber-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.warm,
    socialColor: 'text-stone-400',
    socialHoverColor: 'hover:text-stone-700',
    serviceBg: 'bg-amber-50/50',
    serviceBorder: 'border-amber-100',
    serviceIconBg: 'bg-amber-100 text-amber-700',
    dividerStyle: 'h-px bg-stone-200',
    footerColor: 'text-stone-300',
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    category: 'Photo Header',
    description: 'Crystal ocean waves with cool blue theme',
    pageBg: '#f0f7ff',
    headerBg: '#0c4a6e',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1505118380757-91f5f5632de0?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(12,74,110,0.3) 0%, rgba(12,74,110,0.8) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-sky-100',
    cardShadow: 'shadow-xl shadow-sky-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-sky-900',
    titleColor: 'text-sky-500',
    companyColor: 'text-sky-700',
    labelColor: 'text-sky-300',
    sectionTitleColor: 'text-sky-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.cool,
    socialColor: 'text-sky-400',
    socialHoverColor: 'hover:text-sky-700',
    serviceBg: 'bg-sky-50',
    serviceBorder: 'border-sky-100',
    serviceIconBg: 'bg-sky-100 text-sky-600',
    dividerStyle: 'h-px bg-sky-200',
    footerColor: 'text-sky-300',
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'Photo Header',
    description: 'Lush forest canopy with earthy feel',
    pageBg: '#f0f5f0',
    headerBg: '#1a4731',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1448375240586-882707db888b?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(26,71,49,0.8) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-emerald-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-emerald-900',
    titleColor: 'text-emerald-600',
    companyColor: 'text-emerald-700',
    labelColor: 'text-emerald-400',
    sectionTitleColor: 'text-emerald-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-emerald-600 text-white', email: 'bg-teal-600 text-white', whatsapp: 'bg-green-600 text-white', save: 'bg-emerald-700 text-white' },
    socialColor: 'text-emerald-400',
    socialHoverColor: 'hover:text-emerald-700',
    serviceBg: 'bg-emerald-50',
    serviceBorder: 'border-emerald-100',
    serviceIconBg: 'bg-emerald-100 text-emerald-700',
    dividerStyle: 'h-px bg-emerald-200',
    footerColor: 'text-emerald-300',
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Photo Header',
    description: 'Golden sunset horizon with warm gradient',
    pageBg: '#fff8f0',
    headerBg: '#7c2d12',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1495616811223-4d98c6e9c869?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(124,45,18,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-orange-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-orange-900',
    titleColor: 'text-orange-500',
    companyColor: 'text-orange-700',
    labelColor: 'text-orange-400',
    sectionTitleColor: 'text-orange-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.warm,
    socialColor: 'text-orange-400',
    socialHoverColor: 'hover:text-orange-700',
    serviceBg: 'bg-orange-50',
    serviceBorder: 'border-orange-100',
    serviceIconBg: 'bg-orange-100 text-orange-700',
    dividerStyle: 'h-px bg-orange-200',
    footerColor: 'text-orange-300',
  },
  {
    id: 'abstract-art',
    name: 'Abstract Art',
    category: 'Photo Header',
    description: 'Colorful abstract art header with vibrant palette',
    pageBg: '#faf5ff',
    headerBg: '#581c87',
    headerHeight: 'h-52',
    headerImage: `${UNSPLASH}/photo-1541701494587-cb58502866ab?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(88,28,135,0.6) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-purple-100',
    cardShadow: 'shadow-xl shadow-purple-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-purple-900',
    titleColor: 'text-purple-500',
    companyColor: 'text-purple-700',
    labelColor: 'text-purple-400',
    sectionTitleColor: 'text-purple-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-purple-500 text-white', email: 'bg-fuchsia-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-violet-500 text-white' },
    socialColor: 'text-purple-400',
    socialHoverColor: 'hover:text-purple-700',
    serviceBg: 'bg-purple-50',
    serviceBorder: 'border-purple-100',
    serviceIconBg: 'bg-purple-100 text-purple-600',
    dividerStyle: 'h-px bg-purple-200',
    footerColor: 'text-purple-300',
  },
  {
    id: 'workspace-pro',
    name: 'Workspace Pro',
    category: 'Photo Header',
    description: 'Modern workspace desk with professional vibe',
    pageBg: '#f5f5f5',
    headerBg: '#1f2937',
    headerHeight: 'h-52',
    headerImage: `${UNSPLASH}/photo-1497366216548-37526070297c?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(31,41,55,0.3) 0%, rgba(31,41,55,0.85) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-gray-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-gray-900',
    titleColor: 'text-gray-500',
    companyColor: 'text-gray-700',
    labelColor: 'text-gray-400',
    sectionTitleColor: 'text-gray-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.mono,
    socialColor: 'text-gray-400',
    socialHoverColor: 'hover:text-gray-700',
    serviceBg: 'bg-gray-50',
    serviceBorder: 'border-gray-100',
    serviceIconBg: 'bg-gray-200 text-gray-700',
    dividerStyle: 'h-px bg-gray-200',
    footerColor: 'text-gray-300',
  },
  {
    id: 'tech-circuit',
    name: 'Tech Circuit',
    category: 'Photo Header',
    description: 'Circuit board tech pattern for IT professionals',
    pageBg: '#0f172a',
    headerBg: '#020617',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1518770660439-4636190af475?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(2,6,23,0.4) 0%, rgba(15,23,42,0.95) 100%)',
    cardBg: 'bg-slate-900/80',
    cardBorder: 'border-slate-700',
    cardShadow: 'shadow-2xl shadow-black/30',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-cyan-500/50',
    profileShadow: 'shadow-lg shadow-cyan-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-cyan-400',
    companyColor: 'text-slate-400',
    labelColor: 'text-slate-500',
    sectionTitleColor: 'text-cyan-400',
    fontClass: 'font-mono',
    actionStyle: 'outline',
    actionColors: actions.dark,
    socialColor: 'text-slate-500',
    socialHoverColor: 'hover:text-cyan-400',
    serviceBg: 'bg-slate-800/50',
    serviceBorder: 'border-slate-700',
    serviceIconBg: 'bg-cyan-500/10 text-cyan-400',
    dividerStyle: 'h-px bg-slate-700',
    footerColor: 'text-slate-600',
  },
  {
    id: 'flower-bloom',
    name: 'Flower Bloom',
    category: 'Photo Header',
    description: 'Soft floral background for elegant cards',
    pageBg: '#fdf2f8',
    headerBg: '#831843',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1490750967868-88aa4f44baee?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(131,24,67,0.6) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-pink-100',
    cardShadow: 'shadow-xl shadow-pink-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-pink-900',
    titleColor: 'text-pink-500',
    companyColor: 'text-pink-700',
    labelColor: 'text-pink-300',
    sectionTitleColor: 'text-pink-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-pink-500 text-white', email: 'bg-rose-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-pink-600 text-white' },
    socialColor: 'text-pink-400',
    socialHoverColor: 'hover:text-pink-700',
    serviceBg: 'bg-pink-50',
    serviceBorder: 'border-pink-100',
    serviceIconBg: 'bg-pink-100 text-pink-600',
    dividerStyle: 'h-px bg-pink-200',
    footerColor: 'text-pink-300',
  },
  {
    id: 'night-city',
    name: 'Night City',
    category: 'Photo Header',
    description: 'Neon-lit cityscape for nightlife & entertainment',
    pageBg: '#0a0a0f',
    headerBg: '#0a0a0f',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1519501025264-65ba15a82390?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(10,10,15,0.2) 0%, rgba(10,10,15,0.9) 100%)',
    cardBg: 'bg-gray-900/70',
    cardBorder: 'border-purple-500/20',
    cardShadow: 'shadow-2xl shadow-purple-500/10',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-purple-500/50',
    profileShadow: 'shadow-lg shadow-purple-500/20',
    profileSize: 'w-26 h-26',
    nameColor: 'text-white',
    titleColor: 'text-purple-400',
    companyColor: 'text-gray-400',
    labelColor: 'text-gray-600',
    sectionTitleColor: 'text-purple-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-gray-500',
    socialHoverColor: 'hover:text-purple-400',
    serviceBg: 'bg-white/5',
    serviceBorder: 'border-white/10',
    serviceIconBg: 'bg-purple-500/10 text-purple-400',
    dividerStyle: 'h-px bg-white/10',
    footerColor: 'text-gray-700',
  },

  // ═══════════════════════════════════════════════
  // CATEGORY: GRADIENT HEADERS (26-35)
  // ═══════════════════════════════════════════════
  {
    id: 'royal-blue',
    name: 'Royal Blue',
    category: 'Corporate',
    description: 'Deep royal blue with professional elegance',
    pageBg: '#eff6ff',
    headerBg: 'linear-gradient(135deg, #1e3a8a, #1d4ed8)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-blue-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-blue-900',
    titleColor: 'text-blue-500',
    companyColor: 'text-blue-700',
    labelColor: 'text-blue-300',
    sectionTitleColor: 'text-blue-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-blue-600 text-white', email: 'bg-blue-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-blue-700 text-white' },
    socialColor: 'text-blue-400',
    socialHoverColor: 'hover:text-blue-700',
    serviceBg: 'bg-blue-50',
    serviceBorder: 'border-blue-100',
    serviceIconBg: 'bg-blue-100 text-blue-700',
    dividerStyle: 'h-px bg-blue-200',
    footerColor: 'text-blue-300',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'Premium',
    description: 'Luxurious rose gold gradient with warm elegance',
    pageBg: '#fdf2f8',
    headerBg: 'linear-gradient(135deg, #be185d, #e11d48, #f43f5e)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-rose-100',
    cardShadow: 'shadow-xl shadow-rose-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-rose-900',
    titleColor: 'text-rose-500',
    companyColor: 'text-rose-700',
    labelColor: 'text-rose-300',
    sectionTitleColor: 'text-rose-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-rose-500 text-white', email: 'bg-pink-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-rose-600 text-white' },
    socialColor: 'text-rose-400',
    socialHoverColor: 'hover:text-rose-700',
    serviceBg: 'bg-rose-50',
    serviceBorder: 'border-rose-100',
    serviceIconBg: 'bg-rose-100 text-rose-600',
    dividerStyle: 'h-px bg-rose-200',
    footerColor: 'text-rose-300',
  },
  {
    id: 'emerald-pro',
    name: 'Emerald Pro',
    category: 'Corporate',
    description: 'Rich emerald green for finance & consulting',
    pageBg: '#ecfdf5',
    headerBg: 'linear-gradient(135deg, #064e3b, #047857)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-emerald-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-emerald-900',
    titleColor: 'text-emerald-500',
    companyColor: 'text-emerald-700',
    labelColor: 'text-emerald-400',
    sectionTitleColor: 'text-emerald-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-emerald-600 text-white', email: 'bg-teal-600 text-white', whatsapp: 'bg-green-600 text-white', save: 'bg-emerald-700 text-white' },
    socialColor: 'text-emerald-400',
    socialHoverColor: 'hover:text-emerald-700',
    serviceBg: 'bg-emerald-50',
    serviceBorder: 'border-emerald-100',
    serviceIconBg: 'bg-emerald-100 text-emerald-700',
    dividerStyle: 'h-px bg-emerald-200',
    footerColor: 'text-emerald-300',
  },
  {
    id: 'amber-warmth',
    name: 'Amber Warmth',
    category: 'Creative',
    description: 'Warm amber and orange tones',
    pageBg: '#fffbeb',
    headerBg: 'linear-gradient(135deg, #92400e, #d97706)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-amber-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-amber-900',
    titleColor: 'text-amber-600',
    companyColor: 'text-amber-700',
    labelColor: 'text-amber-400',
    sectionTitleColor: 'text-amber-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.warm,
    socialColor: 'text-amber-400',
    socialHoverColor: 'hover:text-amber-700',
    serviceBg: 'bg-amber-50',
    serviceBorder: 'border-amber-100',
    serviceIconBg: 'bg-amber-100 text-amber-700',
    dividerStyle: 'h-px bg-amber-200',
    footerColor: 'text-amber-300',
  },
  {
    id: 'violet-dream',
    name: 'Violet Dream',
    category: 'Creative',
    description: 'Dreamy violet to purple gradient',
    pageBg: '#faf5ff',
    headerBg: 'linear-gradient(135deg, #5b21b6, #7c3aed, #a78bfa)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-violet-100',
    cardShadow: 'shadow-xl shadow-violet-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-violet-900',
    titleColor: 'text-violet-500',
    companyColor: 'text-violet-700',
    labelColor: 'text-violet-400',
    sectionTitleColor: 'text-violet-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-violet-500 text-white', email: 'bg-purple-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-violet-600 text-white' },
    socialColor: 'text-violet-400',
    socialHoverColor: 'hover:text-violet-700',
    serviceBg: 'bg-violet-50',
    serviceBorder: 'border-violet-100',
    serviceIconBg: 'bg-violet-100 text-violet-600',
    dividerStyle: 'h-px bg-violet-200',
    footerColor: 'text-violet-300',
  },
  {
    id: 'crimson-edge',
    name: 'Crimson Edge',
    category: 'Bold',
    description: 'Bold crimson red with sharp contrast',
    pageBg: '#fef2f2',
    headerBg: 'linear-gradient(135deg, #7f1d1d, #dc2626)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-red-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'square',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-red-900',
    titleColor: 'text-red-500',
    companyColor: 'text-red-700',
    labelColor: 'text-red-400',
    sectionTitleColor: 'text-red-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-red-500 text-white', email: 'bg-red-600 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-red-700 text-white' },
    socialColor: 'text-red-400',
    socialHoverColor: 'hover:text-red-700',
    serviceBg: 'bg-red-50',
    serviceBorder: 'border-red-100',
    serviceIconBg: 'bg-red-100 text-red-600',
    dividerStyle: 'h-px bg-red-200',
    footerColor: 'text-red-300',
  },
  {
    id: 'teal-breeze',
    name: 'Teal Breeze',
    category: 'Lifestyle',
    description: 'Refreshing teal and cyan blend',
    pageBg: '#f0fdfa',
    headerBg: 'linear-gradient(135deg, #134e4a, #0d9488)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-teal-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-teal-900',
    titleColor: 'text-teal-500',
    companyColor: 'text-teal-700',
    labelColor: 'text-teal-400',
    sectionTitleColor: 'text-teal-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.cool,
    socialColor: 'text-teal-400',
    socialHoverColor: 'hover:text-teal-700',
    serviceBg: 'bg-teal-50',
    serviceBorder: 'border-teal-100',
    serviceIconBg: 'bg-teal-100 text-teal-700',
    dividerStyle: 'h-px bg-teal-200',
    footerColor: 'text-teal-300',
  },
  {
    id: 'slate-executive',
    name: 'Slate Executive',
    category: 'Corporate',
    description: 'Sophisticated slate gray for executives',
    pageBg: '#f8fafc',
    headerBg: 'linear-gradient(135deg, #1e293b, #334155)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-slate-900',
    titleColor: 'text-slate-500',
    companyColor: 'text-slate-700',
    labelColor: 'text-slate-400',
    sectionTitleColor: 'text-slate-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.mono,
    socialColor: 'text-slate-400',
    socialHoverColor: 'hover:text-slate-700',
    serviceBg: 'bg-slate-50',
    serviceBorder: 'border-slate-100',
    serviceIconBg: 'bg-slate-200 text-slate-600',
    dividerStyle: 'h-px bg-slate-200',
    footerColor: 'text-slate-300',
  },
  {
    id: 'indigo-night',
    name: 'Indigo Night',
    category: 'Dark',
    description: 'Deep indigo dark mode with glow accents',
    pageBg: '#0f0e1a',
    headerBg: 'linear-gradient(135deg, #1e1b4b, #312e81)',
    headerHeight: 'h-48',
    cardBg: 'bg-indigo-950/60',
    cardBorder: 'border-indigo-800/50',
    cardShadow: 'shadow-2xl shadow-indigo-500/10',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-indigo-400/50',
    profileShadow: 'shadow-lg shadow-indigo-500/30',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-indigo-400',
    companyColor: 'text-indigo-300',
    labelColor: 'text-indigo-500',
    sectionTitleColor: 'text-indigo-400',
    fontClass: '',
    actionStyle: 'outline',
    actionColors: actions.dark,
    socialColor: 'text-indigo-500',
    socialHoverColor: 'hover:text-indigo-300',
    serviceBg: 'bg-indigo-900/30',
    serviceBorder: 'border-indigo-800/30',
    serviceIconBg: 'bg-indigo-500/10 text-indigo-400',
    dividerStyle: 'h-px bg-indigo-800/50',
    footerColor: 'text-indigo-700',
  },
  {
    id: 'coral-sunset',
    name: 'Coral Sunset',
    category: 'Creative',
    description: 'Warm coral to pink gradient blend',
    pageBg: '#fff1f2',
    headerBg: 'linear-gradient(135deg, #f43f5e, #fb923c)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-red-100',
    cardShadow: 'shadow-xl shadow-red-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-red-900',
    titleColor: 'text-red-500',
    companyColor: 'text-orange-600',
    labelColor: 'text-red-300',
    sectionTitleColor: 'text-red-500',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-red-500 text-white', email: 'bg-orange-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-rose-500 text-white' },
    socialColor: 'text-red-400',
    socialHoverColor: 'hover:text-red-600',
    serviceBg: 'bg-red-50',
    serviceBorder: 'border-red-100',
    serviceIconBg: 'bg-red-100 text-red-600',
    dividerStyle: 'h-px bg-red-200',
    footerColor: 'text-red-300',
  },

  // ═══════════════════════════════════════════════
  // CATEGORY: MINIMAL & FLAT (36-45)
  // ═══════════════════════════════════════════════
  {
    id: 'paper-white',
    name: 'Paper White',
    category: 'Minimal',
    description: 'Ultra-clean white with subtle gray accents',
    pageBg: '#ffffff',
    headerBg: 'transparent',
    headerHeight: 'h-0',
    cardBg: 'bg-white',
    cardBorder: 'border-transparent',
    cardShadow: '',
    cardRadius: 'rounded-none',
    profileShape: 'circle',
    profileBorder: 'ring-2 ring-gray-200',
    profileShadow: '',
    profileSize: 'w-24 h-24',
    nameColor: 'text-gray-900',
    titleColor: 'text-gray-400',
    companyColor: 'text-gray-600',
    labelColor: 'text-gray-300',
    sectionTitleColor: 'text-gray-500',
    fontClass: '',
    actionStyle: 'soft',
    actionColors: { call: 'bg-gray-100 text-gray-700', email: 'bg-gray-100 text-gray-700', whatsapp: 'bg-gray-100 text-gray-700', save: 'bg-gray-100 text-gray-700' },
    socialColor: 'text-gray-300',
    socialHoverColor: 'hover:text-gray-600',
    serviceBg: 'bg-gray-50',
    serviceBorder: 'border-gray-100',
    serviceIconBg: 'bg-gray-100 text-gray-600',
    dividerStyle: 'h-px bg-gray-100',
    footerColor: 'text-gray-200',
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    category: 'Minimal',
    description: 'Black and white only — pure contrast',
    pageBg: '#ffffff',
    headerBg: '#000000',
    headerHeight: 'h-40',
    cardBg: 'bg-white',
    cardBorder: 'border-black/10',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-black',
    titleColor: 'text-gray-500',
    companyColor: 'text-black',
    labelColor: 'text-gray-400',
    sectionTitleColor: 'text-black',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.mono,
    socialColor: 'text-gray-400',
    socialHoverColor: 'hover:text-black',
    serviceBg: 'bg-gray-50',
    serviceBorder: 'border-gray-200',
    serviceIconBg: 'bg-black text-white',
    dividerStyle: 'h-px bg-black/10',
    footerColor: 'text-gray-300',
  },
  {
    id: 'pastel-pink',
    name: 'Pastel Pink',
    category: 'Minimal',
    description: 'Soft pastel pink for a gentle touch',
    pageBg: '#fdf2f8',
    headerBg: 'linear-gradient(135deg, #fbcfe8, #f9a8d4)',
    headerHeight: 'h-40',
    cardBg: 'bg-white',
    cardBorder: 'border-pink-100',
    cardShadow: 'shadow-lg shadow-pink-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-md',
    profileSize: 'w-28 h-28',
    nameColor: 'text-pink-900',
    titleColor: 'text-pink-400',
    companyColor: 'text-pink-600',
    labelColor: 'text-pink-300',
    sectionTitleColor: 'text-pink-500',
    fontClass: '',
    actionStyle: 'soft',
    actionColors: { call: 'bg-pink-100 text-pink-700', email: 'bg-pink-100 text-pink-700', whatsapp: 'bg-green-100 text-green-700', save: 'bg-pink-100 text-pink-700' },
    socialColor: 'text-pink-400',
    socialHoverColor: 'hover:text-pink-600',
    serviceBg: 'bg-pink-50',
    serviceBorder: 'border-pink-100',
    serviceIconBg: 'bg-pink-100 text-pink-600',
    dividerStyle: 'h-px bg-pink-200',
    footerColor: 'text-pink-300',
  },
  {
    id: 'pastel-mint',
    name: 'Pastel Mint',
    category: 'Minimal',
    description: 'Fresh mint green pastel style',
    pageBg: '#ecfdf5',
    headerBg: 'linear-gradient(135deg, #a7f3d0, #6ee7b7)',
    headerHeight: 'h-40',
    cardBg: 'bg-white',
    cardBorder: 'border-emerald-100',
    cardShadow: 'shadow-lg shadow-emerald-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-md',
    profileSize: 'w-28 h-28',
    nameColor: 'text-emerald-900',
    titleColor: 'text-emerald-500',
    companyColor: 'text-emerald-600',
    labelColor: 'text-emerald-300',
    sectionTitleColor: 'text-emerald-500',
    fontClass: '',
    actionStyle: 'soft',
    actionColors: { call: 'bg-emerald-100 text-emerald-700', email: 'bg-emerald-100 text-emerald-700', whatsapp: 'bg-green-100 text-green-700', save: 'bg-emerald-100 text-emerald-700' },
    socialColor: 'text-emerald-400',
    socialHoverColor: 'hover:text-emerald-600',
    serviceBg: 'bg-emerald-50',
    serviceBorder: 'border-emerald-100',
    serviceIconBg: 'bg-emerald-100 text-emerald-600',
    dividerStyle: 'h-px bg-emerald-200',
    footerColor: 'text-emerald-300',
  },
  {
    id: 'pastel-lavender',
    name: 'Pastel Lavender',
    category: 'Minimal',
    description: 'Soft lavender for a calming touch',
    pageBg: '#faf5ff',
    headerBg: 'linear-gradient(135deg, #ddd6fe, #c4b5fd)',
    headerHeight: 'h-40',
    cardBg: 'bg-white',
    cardBorder: 'border-violet-100',
    cardShadow: 'shadow-lg shadow-violet-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-md',
    profileSize: 'w-28 h-28',
    nameColor: 'text-violet-900',
    titleColor: 'text-violet-400',
    companyColor: 'text-violet-600',
    labelColor: 'text-violet-300',
    sectionTitleColor: 'text-violet-500',
    fontClass: '',
    actionStyle: 'soft',
    actionColors: { call: 'bg-violet-100 text-violet-700', email: 'bg-violet-100 text-violet-700', whatsapp: 'bg-green-100 text-green-700', save: 'bg-violet-100 text-violet-700' },
    socialColor: 'text-violet-400',
    socialHoverColor: 'hover:text-violet-600',
    serviceBg: 'bg-violet-50',
    serviceBorder: 'border-violet-100',
    serviceIconBg: 'bg-violet-100 text-violet-600',
    dividerStyle: 'h-px bg-violet-200',
    footerColor: 'text-violet-300',
  },
  {
    id: 'charcoal-dark',
    name: 'Charcoal',
    category: 'Dark',
    description: 'Deep charcoal dark mode — sleek and modern',
    pageBg: '#111111',
    headerBg: 'linear-gradient(135deg, #1a1a1a, #2a2a2a)',
    headerHeight: 'h-44',
    cardBg: 'bg-neutral-900',
    cardBorder: 'border-neutral-800',
    cardShadow: 'shadow-2xl shadow-black/30',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-neutral-600',
    profileShadow: 'shadow-xl',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-neutral-400',
    companyColor: 'text-neutral-300',
    labelColor: 'text-neutral-600',
    sectionTitleColor: 'text-neutral-400',
    fontClass: '',
    actionStyle: 'outline',
    actionColors: actions.dark,
    socialColor: 'text-neutral-600',
    socialHoverColor: 'hover:text-neutral-300',
    serviceBg: 'bg-neutral-800/50',
    serviceBorder: 'border-neutral-700',
    serviceIconBg: 'bg-neutral-800 text-neutral-300',
    dividerStyle: 'h-px bg-neutral-800',
    footerColor: 'text-neutral-700',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'Dark',
    description: 'Deep navy midnight with cyan highlights',
    pageBg: '#0c1222',
    headerBg: 'linear-gradient(135deg, #0c1222, #1e3a5f)',
    headerHeight: 'h-44',
    cardBg: 'bg-slate-900/70',
    cardBorder: 'border-sky-900/30',
    cardShadow: 'shadow-2xl shadow-sky-500/5',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'circle',
    profileBorder: 'ring-2 ring-sky-500/40',
    profileShadow: 'shadow-lg shadow-sky-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-sky-400',
    companyColor: 'text-sky-300',
    labelColor: 'text-slate-500',
    sectionTitleColor: 'text-sky-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-slate-500',
    socialHoverColor: 'hover:text-sky-400',
    serviceBg: 'bg-sky-500/5',
    serviceBorder: 'border-sky-500/10',
    serviceIconBg: 'bg-sky-500/10 text-sky-400',
    dividerStyle: 'h-px bg-sky-900/30',
    footerColor: 'text-slate-700',
  },
  {
    id: 'dark-forest',
    name: 'Dark Forest',
    category: 'Dark',
    description: 'Dark green forest with emerald glow',
    pageBg: '#071210',
    headerBg: 'linear-gradient(135deg, #071210, #14532d)',
    headerHeight: 'h-44',
    cardBg: 'bg-emerald-950/60',
    cardBorder: 'border-emerald-800/30',
    cardShadow: 'shadow-2xl shadow-emerald-500/5',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'circle',
    profileBorder: 'ring-2 ring-emerald-500/40',
    profileShadow: 'shadow-lg shadow-emerald-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-emerald-400',
    companyColor: 'text-emerald-300',
    labelColor: 'text-emerald-700',
    sectionTitleColor: 'text-emerald-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-emerald-700',
    socialHoverColor: 'hover:text-emerald-400',
    serviceBg: 'bg-emerald-500/5',
    serviceBorder: 'border-emerald-500/10',
    serviceIconBg: 'bg-emerald-500/10 text-emerald-400',
    dividerStyle: 'h-px bg-emerald-900/30',
    footerColor: 'text-emerald-800',
  },
  {
    id: 'swiss-grid',
    name: 'Swiss Grid',
    category: 'Minimal',
    description: 'International typographic style — grid-based',
    pageBg: '#ffffff',
    headerBg: '#000000',
    headerHeight: 'h-32',
    headerPattern: 'repeating-linear-gradient(90deg, transparent, transparent 79px, rgba(255,255,255,0.05) 79px, rgba(255,255,255,0.05) 80px)',
    cardBg: 'bg-white',
    cardBorder: 'border-black/5',
    cardShadow: '',
    cardRadius: 'rounded-none',
    profileShape: 'square',
    profileBorder: 'ring-0',
    profileShadow: '',
    profileSize: 'w-24 h-24',
    nameColor: 'text-black',
    titleColor: 'text-gray-500',
    companyColor: 'text-black',
    labelColor: 'text-gray-400',
    sectionTitleColor: 'text-red-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-red-600 text-white', email: 'bg-black text-white', whatsapp: 'bg-black text-white', save: 'bg-red-600 text-white' },
    socialColor: 'text-gray-400',
    socialHoverColor: 'hover:text-black',
    serviceBg: 'bg-gray-50',
    serviceBorder: 'border-black/5',
    serviceIconBg: 'bg-red-600 text-white',
    dividerStyle: 'h-0.5 bg-black',
    footerColor: 'text-gray-300',
  },
  {
    id: 'peach-cream',
    name: 'Peach Cream',
    category: 'Minimal',
    description: 'Warm peach tones with creamy background',
    pageBg: '#fef3e2',
    headerBg: 'linear-gradient(135deg, #fdba74, #fb923c)',
    headerHeight: 'h-40',
    cardBg: 'bg-white',
    cardBorder: 'border-orange-100',
    cardShadow: 'shadow-lg shadow-orange-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-md',
    profileSize: 'w-28 h-28',
    nameColor: 'text-orange-900',
    titleColor: 'text-orange-400',
    companyColor: 'text-orange-600',
    labelColor: 'text-orange-300',
    sectionTitleColor: 'text-orange-500',
    fontClass: '',
    actionStyle: 'soft',
    actionColors: { call: 'bg-orange-100 text-orange-700', email: 'bg-orange-100 text-orange-700', whatsapp: 'bg-green-100 text-green-700', save: 'bg-orange-100 text-orange-700' },
    socialColor: 'text-orange-400',
    socialHoverColor: 'hover:text-orange-600',
    serviceBg: 'bg-orange-50',
    serviceBorder: 'border-orange-100',
    serviceIconBg: 'bg-orange-100 text-orange-600',
    dividerStyle: 'h-px bg-orange-200',
    footerColor: 'text-orange-300',
  },

  // ═══════════════════════════════════════════════
  // CATEGORY: PATTERN-BASED & SPECIAL (46-50)
  // ═══════════════════════════════════════════════
  {
    id: 'marble-luxury',
    name: 'Marble Luxury',
    category: 'Premium',
    description: 'White marble texture with gold accents',
    pageBg: '#f9f9f7',
    headerBg: '#1a1a1a',
    headerHeight: 'h-48',
    headerImage: `${UNSPLASH}/photo-1558618666-fcd25c85f82e?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.4) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-amber-200/50',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-amber-200',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-gray-900',
    titleColor: 'text-amber-600',
    companyColor: 'text-gray-700',
    labelColor: 'text-amber-400',
    sectionTitleColor: 'text-amber-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-amber-500 text-white', email: 'bg-gray-800 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-amber-600 text-white' },
    socialColor: 'text-amber-400',
    socialHoverColor: 'hover:text-amber-600',
    serviceBg: 'bg-amber-50/50',
    serviceBorder: 'border-amber-200/50',
    serviceIconBg: 'bg-amber-100 text-amber-700',
    dividerStyle: 'h-px bg-amber-200',
    footerColor: 'text-amber-300',
  },
  {
    id: 'sapphire-blue',
    name: 'Sapphire Blue',
    category: 'Premium',
    description: 'Deep sapphire with crystalline shine',
    pageBg: '#0c1631',
    headerBg: 'linear-gradient(135deg, #0c1631, #1e40af, #1e3a8a)',
    headerHeight: 'h-48',
    cardBg: 'bg-blue-950/60',
    cardBorder: 'border-blue-700/30',
    cardShadow: 'shadow-2xl shadow-blue-500/10',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'circle',
    profileBorder: 'ring-2 ring-blue-400/50',
    profileShadow: 'shadow-lg shadow-blue-500/30',
    profileSize: 'w-28 h-28',
    nameColor: 'text-white',
    titleColor: 'text-blue-300',
    companyColor: 'text-blue-200',
    labelColor: 'text-blue-600',
    sectionTitleColor: 'text-blue-300',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-blue-500',
    socialHoverColor: 'hover:text-blue-300',
    serviceBg: 'bg-blue-500/5',
    serviceBorder: 'border-blue-500/10',
    serviceIconBg: 'bg-blue-500/10 text-blue-300',
    dividerStyle: 'h-px bg-blue-800/50',
    footerColor: 'text-blue-800',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    category: 'Photo Header',
    description: 'Japanese cherry blossom spring theme',
    pageBg: '#fdf2f8',
    headerBg: '#881337',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1522383225653-ed111181a951?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(136,19,55,0.5) 100%)',
    cardBg: 'bg-white/95',
    cardBorder: 'border-pink-200',
    cardShadow: 'shadow-xl shadow-pink-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-pink-900',
    titleColor: 'text-pink-500',
    companyColor: 'text-pink-700',
    labelColor: 'text-pink-300',
    sectionTitleColor: 'text-pink-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-pink-500 text-white', email: 'bg-rose-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-pink-600 text-white' },
    socialColor: 'text-pink-400',
    socialHoverColor: 'hover:text-pink-600',
    serviceBg: 'bg-pink-50',
    serviceBorder: 'border-pink-100',
    serviceIconBg: 'bg-pink-100 text-pink-600',
    dividerStyle: 'h-px bg-pink-200',
    footerColor: 'text-pink-300',
  },
  {
    id: 'aurora-sky',
    name: 'Aurora Sky',
    category: 'Creative',
    description: 'Northern lights gradient with cosmic feel',
    pageBg: '#030712',
    headerBg: 'linear-gradient(135deg, #064e3b, #1e3a8a, #581c87)',
    headerHeight: 'h-52',
    cardBg: 'bg-gray-900/60',
    cardBorder: 'border-emerald-500/10',
    cardShadow: 'shadow-2xl',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'circle',
    profileBorder: 'ring-2 ring-emerald-400/40',
    profileShadow: 'shadow-lg shadow-emerald-500/20',
    profileSize: 'w-28 h-28',
    nameColor: 'text-white',
    titleColor: 'text-emerald-400',
    companyColor: 'text-purple-300',
    labelColor: 'text-gray-600',
    sectionTitleColor: 'text-emerald-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-gray-500',
    socialHoverColor: 'hover:text-emerald-400',
    serviceBg: 'bg-emerald-500/5',
    serviceBorder: 'border-emerald-500/10',
    serviceIconBg: 'bg-emerald-500/10 text-emerald-400',
    dividerStyle: 'h-px bg-gray-800',
    footerColor: 'text-gray-700',
  },
  {
    id: 'construction-pro',
    name: 'Construction Pro',
    category: 'Photo Header',
    description: 'Bold construction site header for builders',
    pageBg: '#fafaf9',
    headerBg: '#292524',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1504307651254-35680f356dfd?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(41,37,36,0.85) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-yellow-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-stone-900',
    titleColor: 'text-yellow-600',
    companyColor: 'text-stone-700',
    labelColor: 'text-stone-400',
    sectionTitleColor: 'text-yellow-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-yellow-500 text-black', email: 'bg-stone-800 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-yellow-600 text-black' },
    socialColor: 'text-stone-400',
    socialHoverColor: 'hover:text-stone-700',
    serviceBg: 'bg-yellow-50',
    serviceBorder: 'border-yellow-200',
    serviceIconBg: 'bg-yellow-100 text-yellow-700',
    dividerStyle: 'h-1 bg-yellow-400',
    footerColor: 'text-stone-300',
  },

  // ═══════════════════════════════════════════════
  // CATEGORY: MORE PHOTO HEADERS & STYLES (51-65)
  // ═══════════════════════════════════════════════
  {
    id: 'coffee-shop',
    name: 'Coffee Shop',
    category: 'Photo Header',
    description: 'Cozy cafe ambiance for food & beverage',
    pageBg: '#faf7f2',
    headerBg: '#3e2723',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1501339847302-ac426a4a7cbb?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(62,39,35,0.8) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-amber-200/50',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-amber-900',
    titleColor: 'text-amber-600',
    companyColor: 'text-amber-700',
    labelColor: 'text-amber-400',
    sectionTitleColor: 'text-amber-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-amber-700 text-white', email: 'bg-amber-600 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-amber-800 text-white' },
    socialColor: 'text-amber-400',
    socialHoverColor: 'hover:text-amber-700',
    serviceBg: 'bg-amber-50',
    serviceBorder: 'border-amber-100',
    serviceIconBg: 'bg-amber-100 text-amber-700',
    dividerStyle: 'h-px bg-amber-200',
    footerColor: 'text-amber-300',
  },
  {
    id: 'fitness-energy',
    name: 'Fitness Energy',
    category: 'Photo Header',
    description: 'High-energy gym theme for fitness pros',
    pageBg: '#111111',
    headerBg: '#111111',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1534438327276-14e5300c3a48?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.3) 0%, rgba(17,17,17,0.9) 100%)',
    cardBg: 'bg-neutral-900',
    cardBorder: 'border-lime-500/20',
    cardShadow: 'shadow-2xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-lime-500/50',
    profileShadow: 'shadow-lg shadow-lime-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-lime-400',
    companyColor: 'text-neutral-400',
    labelColor: 'text-neutral-600',
    sectionTitleColor: 'text-lime-400',
    fontClass: '',
    actionStyle: 'outline',
    actionColors: { call: 'bg-lime-500/20 text-lime-400 border border-lime-500/30', email: 'bg-neutral-800 text-neutral-300 border border-neutral-700', whatsapp: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30', save: 'bg-lime-500/20 text-lime-400 border border-lime-500/30' },
    socialColor: 'text-neutral-600',
    socialHoverColor: 'hover:text-lime-400',
    serviceBg: 'bg-neutral-800/50',
    serviceBorder: 'border-neutral-700',
    serviceIconBg: 'bg-lime-500/10 text-lime-400',
    dividerStyle: 'h-px bg-neutral-800',
    footerColor: 'text-neutral-700',
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    category: 'Photo Header',
    description: 'Luxury property showcase for realtors',
    pageBg: '#f8f6f3',
    headerBg: '#1c1917',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1600596542815-ffad4c1539a9?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(28,25,23,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-stone-900',
    titleColor: 'text-stone-500',
    companyColor: 'text-stone-700',
    labelColor: 'text-stone-400',
    sectionTitleColor: 'text-stone-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-stone-800 text-white', email: 'bg-stone-700 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-stone-900 text-white' },
    socialColor: 'text-stone-400',
    socialHoverColor: 'hover:text-stone-700',
    serviceBg: 'bg-stone-50',
    serviceBorder: 'border-stone-100',
    serviceIconBg: 'bg-stone-200 text-stone-700',
    dividerStyle: 'h-px bg-stone-200',
    footerColor: 'text-stone-300',
  },
  {
    id: 'medical-care',
    name: 'Medical Care',
    category: 'Corporate',
    description: 'Clean medical blue for healthcare professionals',
    pageBg: '#f0f9ff',
    headerBg: 'linear-gradient(135deg, #0369a1, #0284c7)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-sky-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-sky-900',
    titleColor: 'text-sky-600',
    companyColor: 'text-sky-700',
    labelColor: 'text-sky-400',
    sectionTitleColor: 'text-sky-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-sky-600 text-white', email: 'bg-sky-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-sky-700 text-white' },
    socialColor: 'text-sky-400',
    socialHoverColor: 'hover:text-sky-700',
    serviceBg: 'bg-sky-50',
    serviceBorder: 'border-sky-100',
    serviceIconBg: 'bg-sky-100 text-sky-600',
    dividerStyle: 'h-px bg-sky-200',
    footerColor: 'text-sky-300',
  },
  {
    id: 'legal-authority',
    name: 'Legal Authority',
    category: 'Corporate',
    description: 'Authoritative dark navy for legal professionals',
    pageBg: '#f1f5f9',
    headerBg: 'linear-gradient(135deg, #0f172a, #1e293b)',
    headerHeight: 'h-48',
    headerPattern: 'repeating-linear-gradient(45deg, transparent, transparent 20px, rgba(255,255,255,0.02) 20px, rgba(255,255,255,0.02) 40px)',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-slate-900',
    titleColor: 'text-slate-500',
    companyColor: 'text-slate-700',
    labelColor: 'text-slate-400',
    sectionTitleColor: 'text-slate-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-slate-800 text-white', email: 'bg-slate-700 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-slate-900 text-white' },
    socialColor: 'text-slate-400',
    socialHoverColor: 'hover:text-slate-700',
    serviceBg: 'bg-slate-50',
    serviceBorder: 'border-slate-100',
    serviceIconBg: 'bg-slate-200 text-slate-700',
    dividerStyle: 'h-px bg-slate-200',
    footerColor: 'text-slate-300',
  },
  {
    id: 'food-delight',
    name: 'Food Delight',
    category: 'Photo Header',
    description: 'Vibrant food photography for restaurants',
    pageBg: '#fffbeb',
    headerBg: '#92400e',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(146,64,14,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-orange-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-orange-900',
    titleColor: 'text-orange-500',
    companyColor: 'text-orange-700',
    labelColor: 'text-orange-400',
    sectionTitleColor: 'text-orange-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.warm,
    socialColor: 'text-orange-400',
    socialHoverColor: 'hover:text-orange-700',
    serviceBg: 'bg-orange-50',
    serviceBorder: 'border-orange-100',
    serviceIconBg: 'bg-orange-100 text-orange-600',
    dividerStyle: 'h-px bg-orange-200',
    footerColor: 'text-orange-300',
  },
  {
    id: 'education-hub',
    name: 'Education Hub',
    category: 'Corporate',
    description: 'Academic theme for teachers & educators',
    pageBg: '#eff6ff',
    headerBg: 'linear-gradient(135deg, #1e3a5f, #2563eb)',
    headerHeight: 'h-48',
    cardBg: 'bg-white',
    cardBorder: 'border-blue-100',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-blue-900',
    titleColor: 'text-blue-500',
    companyColor: 'text-blue-700',
    labelColor: 'text-blue-300',
    sectionTitleColor: 'text-blue-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-blue-600 text-white', email: 'bg-blue-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-blue-700 text-white' },
    socialColor: 'text-blue-400',
    socialHoverColor: 'hover:text-blue-700',
    serviceBg: 'bg-blue-50',
    serviceBorder: 'border-blue-100',
    serviceIconBg: 'bg-blue-100 text-blue-600',
    dividerStyle: 'h-px bg-blue-200',
    footerColor: 'text-blue-300',
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    category: 'Photo Header',
    description: 'Artistic creative workspace for designers',
    pageBg: '#faf5ff',
    headerBg: '#4c1d95',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1513364776144-60967b0f800f?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(76,29,149,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-purple-100',
    cardShadow: 'shadow-xl shadow-purple-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'rounded',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-purple-900',
    titleColor: 'text-purple-500',
    companyColor: 'text-purple-700',
    labelColor: 'text-purple-400',
    sectionTitleColor: 'text-purple-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-purple-500 text-white', email: 'bg-fuchsia-500 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-purple-600 text-white' },
    socialColor: 'text-purple-400',
    socialHoverColor: 'hover:text-purple-700',
    serviceBg: 'bg-purple-50',
    serviceBorder: 'border-purple-100',
    serviceIconBg: 'bg-purple-100 text-purple-600',
    dividerStyle: 'h-px bg-purple-200',
    footerColor: 'text-purple-300',
  },
  {
    id: 'music-beats',
    name: 'Music Beats',
    category: 'Dark',
    description: 'Dark theme with vibrant pink for musicians',
    pageBg: '#0a0a0a',
    headerBg: 'linear-gradient(135deg, #0a0a0a, #831843)',
    headerHeight: 'h-48',
    cardBg: 'bg-neutral-900/80',
    cardBorder: 'border-pink-500/20',
    cardShadow: 'shadow-2xl shadow-pink-500/10',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-pink-500/50',
    profileShadow: 'shadow-lg shadow-pink-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-pink-400',
    companyColor: 'text-neutral-400',
    labelColor: 'text-neutral-600',
    sectionTitleColor: 'text-pink-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-neutral-600',
    socialHoverColor: 'hover:text-pink-400',
    serviceBg: 'bg-pink-500/5',
    serviceBorder: 'border-pink-500/10',
    serviceIconBg: 'bg-pink-500/10 text-pink-400',
    dividerStyle: 'h-px bg-neutral-800',
    footerColor: 'text-neutral-700',
  },
  {
    id: 'travel-wanderer',
    name: 'Travel Wanderer',
    category: 'Photo Header',
    description: 'Adventure travel theme with desert landscape',
    pageBg: '#fef3c7',
    headerBg: '#78350f',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1469854523086-cc02fe5d8800?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(120,53,15,0.7) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-yellow-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-yellow-900',
    titleColor: 'text-yellow-600',
    companyColor: 'text-yellow-700',
    labelColor: 'text-yellow-400',
    sectionTitleColor: 'text-yellow-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-yellow-600 text-white', email: 'bg-amber-600 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-yellow-700 text-white' },
    socialColor: 'text-yellow-500',
    socialHoverColor: 'hover:text-yellow-700',
    serviceBg: 'bg-yellow-50',
    serviceBorder: 'border-yellow-200',
    serviceIconBg: 'bg-yellow-100 text-yellow-700',
    dividerStyle: 'h-px bg-yellow-300',
    footerColor: 'text-yellow-400',
  },
  {
    id: 'auto-garage',
    name: 'Auto Garage',
    category: 'Photo Header',
    description: 'Bold automotive theme for car businesses',
    pageBg: '#18181b',
    headerBg: '#18181b',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1492144534655-ae79c964c9d7?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(24,24,27,0.9) 100%)',
    cardBg: 'bg-zinc-900',
    cardBorder: 'border-red-500/20',
    cardShadow: 'shadow-2xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-red-500/50',
    profileShadow: 'shadow-lg shadow-red-500/20',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-red-400',
    companyColor: 'text-zinc-400',
    labelColor: 'text-zinc-600',
    sectionTitleColor: 'text-red-400',
    fontClass: '',
    actionStyle: 'outline',
    actionColors: { call: 'bg-red-500/20 text-red-400 border border-red-500/30', email: 'bg-zinc-800 text-zinc-300 border border-zinc-700', whatsapp: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30', save: 'bg-red-500/20 text-red-400 border border-red-500/30' },
    socialColor: 'text-zinc-600',
    socialHoverColor: 'hover:text-red-400',
    serviceBg: 'bg-zinc-800/50',
    serviceBorder: 'border-zinc-700',
    serviceIconBg: 'bg-red-500/10 text-red-400',
    dividerStyle: 'h-px bg-zinc-800',
    footerColor: 'text-zinc-700',
  },
  {
    id: 'wedding-bliss',
    name: 'Wedding Bliss',
    category: 'Photo Header',
    description: 'Elegant wedding theme for event planners',
    pageBg: '#fdf2f8',
    headerBg: '#831843',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1519741497674-611481863552?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(131,24,67,0.5) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-pink-100',
    cardShadow: 'shadow-xl shadow-pink-100/50',
    cardRadius: 'rounded-3xl',
    profileShape: 'circle',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-28 h-28',
    nameColor: 'text-pink-900',
    titleColor: 'text-pink-500',
    companyColor: 'text-pink-700',
    labelColor: 'text-pink-300',
    sectionTitleColor: 'text-pink-600',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: { call: 'bg-pink-500 text-white', email: 'bg-rose-400 text-white', whatsapp: 'bg-emerald-500 text-white', save: 'bg-pink-600 text-white' },
    socialColor: 'text-pink-400',
    socialHoverColor: 'hover:text-pink-600',
    serviceBg: 'bg-pink-50',
    serviceBorder: 'border-pink-100',
    serviceIconBg: 'bg-pink-100 text-pink-600',
    dividerStyle: 'h-px bg-pink-200',
    footerColor: 'text-pink-300',
  },
  {
    id: 'gaming-zone',
    name: 'Gaming Zone',
    category: 'Dark',
    description: 'RGB gaming aesthetic for gamers & streamers',
    pageBg: '#09090b',
    headerBg: 'linear-gradient(135deg, #09090b, #18181b)',
    headerHeight: 'h-48',
    cardBg: 'bg-zinc-900/80',
    cardBorder: 'border-violet-500/20',
    cardShadow: 'shadow-2xl shadow-violet-500/10',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'square',
    profileBorder: 'ring-2 ring-violet-500/60',
    profileShadow: 'shadow-lg shadow-violet-500/30',
    profileSize: 'w-24 h-24',
    nameColor: 'text-white',
    titleColor: 'text-violet-400',
    companyColor: 'text-zinc-400',
    labelColor: 'text-zinc-600',
    sectionTitleColor: 'text-violet-400',
    fontClass: 'font-mono',
    actionStyle: 'outline',
    actionColors: { call: 'bg-violet-500/20 text-violet-400 border border-violet-500/30', email: 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30', whatsapp: 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30', save: 'bg-fuchsia-500/20 text-fuchsia-400 border border-fuchsia-500/30' },
    socialColor: 'text-zinc-600',
    socialHoverColor: 'hover:text-violet-400',
    serviceBg: 'bg-violet-500/5',
    serviceBorder: 'border-violet-500/10',
    serviceIconBg: 'bg-violet-500/10 text-violet-400',
    dividerStyle: 'h-px bg-zinc-800',
    footerColor: 'text-zinc-700',
  },
  {
    id: 'architect-studio',
    name: 'Architect Studio',
    category: 'Photo Header',
    description: 'Clean architectural lines for architects',
    pageBg: '#f5f5f4',
    headerBg: '#1c1917',
    headerHeight: 'h-56',
    headerImage: `${UNSPLASH}/photo-1487958449943-2429e8be8625?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(28,25,23,0.8) 100%)',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200',
    cardShadow: 'shadow-xl',
    cardRadius: 'rounded-2xl',
    profileShape: 'square',
    profileBorder: 'ring-4 ring-white',
    profileShadow: 'shadow-lg',
    profileSize: 'w-24 h-24',
    nameColor: 'text-stone-900',
    titleColor: 'text-stone-500',
    companyColor: 'text-stone-700',
    labelColor: 'text-stone-400',
    sectionTitleColor: 'text-stone-700',
    fontClass: '',
    actionStyle: 'filled',
    actionColors: actions.mono,
    socialColor: 'text-stone-400',
    socialHoverColor: 'hover:text-stone-700',
    serviceBg: 'bg-stone-50',
    serviceBorder: 'border-stone-100',
    serviceIconBg: 'bg-stone-200 text-stone-700',
    dividerStyle: 'h-px bg-stone-200',
    footerColor: 'text-stone-300',
  },
  {
    id: 'photography-pro',
    name: 'Photography Pro',
    category: 'Photo Header',
    description: 'Dramatic dark theme for photographers',
    pageBg: '#0a0a0a',
    headerBg: '#0a0a0a',
    headerHeight: 'h-60',
    headerImage: `${UNSPLASH}/photo-1452587925148-ce544e77e70d?w=800&h=400&fit=crop`,
    headerOverlay: 'linear-gradient(180deg, rgba(0,0,0,0) 30%, rgba(10,10,10,1) 100%)',
    cardBg: 'bg-neutral-900/50',
    cardBorder: 'border-neutral-800',
    cardShadow: 'shadow-2xl',
    cardRadius: 'rounded-2xl',
    cardBlur: true,
    profileShape: 'rounded',
    profileBorder: 'ring-2 ring-white/30',
    profileShadow: 'shadow-xl',
    profileSize: 'w-28 h-28',
    nameColor: 'text-white',
    titleColor: 'text-neutral-400',
    companyColor: 'text-neutral-300',
    labelColor: 'text-neutral-600',
    sectionTitleColor: 'text-neutral-400',
    fontClass: '',
    actionStyle: 'glass',
    actionColors: actions.glass,
    socialColor: 'text-neutral-600',
    socialHoverColor: 'hover:text-white',
    serviceBg: 'bg-white/5',
    serviceBorder: 'border-white/10',
    serviceIconBg: 'bg-white/10 text-white',
    dividerStyle: 'h-px bg-neutral-800',
    footerColor: 'text-neutral-700',
  },
];
