"""add minisites table

Revision ID: 33d38320c2d1
Revises: f2985517f302
Create Date: 2026-04-01 15:35:25.177564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d38320c2d1'
down_revision: Union[str, None] = 'f2985517f302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='minisitestatus'), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('hero_title', sa.String(length=300), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=100), nullable=True),
    sa.Column('hero_cta_url', sa.String(length=500), nullable=True),
    sa.Column('about_title', sa.String(length=200), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('about_image_url', sa.String(length=500), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('testimonials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_title', sa.String(length=300), nullable=True),
    sa.Column('cta_subtitle', sa.Text(), nullable=True),
    sa.Column('cta_button_text', sa.String(length=100), nullable=True),
    sa.Column('cta_button_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('instagram', sa.String(length=500), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('twitter', sa.String(length=500), nullable=True),
    sa.Column('youtube', sa.String(length=500), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('custom_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minisites_id'), 'minisites', ['id'], unique=False)
    op.create_index(op.f('ix_minisites_slug'), 'minisites', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_minisites_slug'), table_name='minisites')
    op.drop_index(op.f('ix_minisites_id'), table_name='minisites')
    op.drop_table('minisites')
    # ### end Alembic commands ###
