"""add template_id to restaurants

Revision ID: 8b9c6f4e733c
Revises: 3bed9b3c350b
Create Date: 2026-04-03 21:35:31.274175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9c6f4e733c'
down_revision: Union[str, None] = '3bed9b3c350b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('template_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'template_id')
    # ### end Alembic commands ###
