export interface MenuTemplateConfig {
  id: string;
  name: string;
  description: string;
  category: 'minimal' | 'modern' | 'luxury' | 'casual' | 'ethnic' | 'cafe' | 'fast-food' | 'fine-dining' | 'bar' | 'bakery';
  preview: string;

  header: {
    layout: 'centered' | 'left-aligned' | 'overlay' | 'split' | 'minimal-bar';
    bgStyle: string;
    textColor: string;
    logoSize: 'sm' | 'md' | 'lg';
    showCover: boolean;
    overlay?: string;
  };

  categoryNav: {
    style: 'pills' | 'tabs' | 'underline' | 'chips' | 'sidebar' | 'scroll-cards';
    bgStyle: string;
    activeStyle: string;
    textColor: string;
    position: 'sticky-top' | 'inline' | 'floating';
  };

  itemCard: {
    layout: 'horizontal' | 'vertical' | 'compact' | 'detailed' | 'grid-square';
    bgStyle: string;
    borderStyle: string;
    imageStyle: 'rounded' | 'square' | 'circle' | 'none';
    imageSize: 'sm' | 'md' | 'lg';
    priceStyle: string;
    nameStyle: string;
    descStyle: string;
    showImage: boolean;
    shadow: string;
    hoverEffect: string;
  };

  page: {
    bgStyle: string;
    fontFamily: string;
    accentColor: string;
    borderRadius: string;
    spacing: 'compact' | 'normal' | 'spacious';
  };

  cartButton: {
    style: string;
    position: 'bottom-center' | 'bottom-right' | 'floating';
    shape: 'rounded' | 'pill' | 'square';
  };

  dietBadge: {
    style: 'dot' | 'tag' | 'icon' | 'border';
  };
}

export const menuTemplateConfigs: MenuTemplateConfig[] = [
  // ============================================================
  // MINIMAL / CLEAN DESIGNS (1-8)
  // ============================================================
  {
    id: 'minimal-white',
    name: 'Pure White',
    description: 'Ultra-clean white canvas with subtle gray accents and generous whitespace.',
    category: 'minimal',
    preview: '🤍',
    header: {
      layout: 'centered',
      bgStyle: 'bg-white',
      textColor: 'text-gray-900',
      logoSize: 'md',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-white',
      activeStyle: 'border-b-2 border-gray-900 text-gray-900',
      textColor: 'text-gray-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border-b border-gray-100',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-gray-900 font-medium text-sm',
      nameStyle: 'text-gray-900 font-medium text-base',
      descStyle: 'text-gray-400 text-sm',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-gray-50 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-white',
      fontFamily: 'font-sans',
      accentColor: 'gray-900',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-gray-900 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'minimal-mono',
    name: 'Monochrome Ink',
    description: 'Black-and-white typographic menu inspired by editorial design.',
    category: 'minimal',
    preview: '🖤',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-black',
      textColor: 'text-white',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-black',
      activeStyle: 'bg-white text-black',
      textColor: 'text-gray-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'compact',
      bgStyle: 'bg-white',
      borderStyle: 'border-b border-black',
      imageStyle: 'none',
      imageSize: 'sm',
      priceStyle: 'text-black font-bold text-base',
      nameStyle: 'text-black font-bold uppercase tracking-wide text-sm',
      descStyle: 'text-gray-600 text-xs italic',
      showImage: false,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-gray-100 transition-colors duration-150',
    },
    page: {
      bgStyle: 'bg-white',
      fontFamily: 'font-mono',
      accentColor: 'black',
      borderRadius: 'rounded-none',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-black text-white',
      position: 'bottom-right',
      shape: 'square',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'minimal-sand',
    name: 'Sand Dune',
    description: 'Warm beige and tan palette with a calm, organic feel.',
    category: 'minimal',
    preview: '🏜️',
    header: {
      layout: 'centered',
      bgStyle: 'bg-amber-50',
      textColor: 'text-amber-900',
      logoSize: 'md',
      showCover: false,
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-amber-50',
      activeStyle: 'bg-amber-800 text-white',
      textColor: 'text-amber-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border border-amber-100',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-amber-800 font-semibold',
      nameStyle: 'text-amber-900 font-medium',
      descStyle: 'text-amber-600 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-amber-50',
      fontFamily: 'font-sans',
      accentColor: 'amber-800',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-800 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'minimal-sage',
    name: 'Sage Garden',
    description: 'Muted sage green with soft rounded edges for a natural aesthetic.',
    category: 'minimal',
    preview: '🌿',
    header: {
      layout: 'centered',
      bgStyle: 'bg-green-50',
      textColor: 'text-green-900',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-green-50/80 to-green-50',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-green-50',
      activeStyle: 'bg-green-700 text-white',
      textColor: 'text-green-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-green-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-green-800 font-semibold',
      nameStyle: 'text-green-900 font-medium',
      descStyle: 'text-green-600 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-0.5 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-green-50',
      fontFamily: 'font-sans',
      accentColor: 'green-700',
      borderRadius: 'rounded-2xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-green-700 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'minimal-paper',
    name: 'Paper Craft',
    description: 'Warm off-white with dotted borders evoking handwritten menus.',
    category: 'minimal',
    preview: '📄',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-stone-50',
      textColor: 'text-stone-800',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-stone-50',
      activeStyle: 'border-b-2 border-stone-700 text-stone-800',
      textColor: 'text-stone-400',
      position: 'inline',
    },
    itemCard: {
      layout: 'compact',
      bgStyle: 'bg-stone-50',
      borderStyle: 'border-b border-dashed border-stone-300',
      imageStyle: 'none',
      imageSize: 'sm',
      priceStyle: 'text-stone-700 font-semibold',
      nameStyle: 'text-stone-800 font-medium',
      descStyle: 'text-stone-500 text-sm italic',
      showImage: false,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-stone-100 transition-colors duration-150',
    },
    page: {
      bgStyle: 'bg-stone-50',
      fontFamily: 'font-serif',
      accentColor: 'stone-700',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-stone-700 text-white',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'minimal-frost',
    name: 'Arctic Frost',
    description: 'Cool blue-gray minimal palette with frosted glass elements.',
    category: 'minimal',
    preview: '❄️',
    header: {
      layout: 'minimal-bar',
      bgStyle: 'bg-slate-50',
      textColor: 'text-slate-800',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-white/60 backdrop-blur-md',
      activeStyle: 'bg-slate-700 text-white',
      textColor: 'text-slate-500',
      position: 'floating',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white/70 backdrop-blur-sm',
      borderStyle: 'border border-slate-200/50',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-slate-700 font-medium',
      nameStyle: 'text-slate-800 font-medium',
      descStyle: 'text-slate-400 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:bg-white hover:shadow-md transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-gradient-to-b from-slate-100 to-blue-50',
      fontFamily: 'font-sans',
      accentColor: 'slate-700',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-slate-700 text-white backdrop-blur-sm',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'minimal-blush',
    name: 'Blush Petal',
    description: 'Soft pink and rose with delicate typography for elegant minimalism.',
    category: 'minimal',
    preview: '🌸',
    header: {
      layout: 'centered',
      bgStyle: 'bg-rose-50',
      textColor: 'text-rose-900',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-rose-50/90 to-rose-50',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-rose-50',
      activeStyle: 'border-b-2 border-rose-400 text-rose-700',
      textColor: 'text-rose-300',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-rose-100',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-rose-600 font-semibold',
      nameStyle: 'text-rose-900 font-medium',
      descStyle: 'text-rose-400 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md hover:border-rose-200 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-rose-50',
      fontFamily: 'font-serif',
      accentColor: 'rose-500',
      borderRadius: 'rounded-xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-rose-500 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'minimal-concrete',
    name: 'Raw Concrete',
    description: 'Industrial gray with sharp edges and bold type for a brutalist vibe.',
    category: 'minimal',
    preview: '🏗️',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-neutral-200',
      textColor: 'text-neutral-900',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-neutral-200',
      activeStyle: 'bg-neutral-800 text-white',
      textColor: 'text-neutral-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'compact',
      bgStyle: 'bg-neutral-100',
      borderStyle: 'border-l-4 border-neutral-800',
      imageStyle: 'square',
      imageSize: 'sm',
      priceStyle: 'text-neutral-800 font-bold',
      nameStyle: 'text-neutral-900 font-bold uppercase tracking-wider text-sm',
      descStyle: 'text-neutral-500 text-xs',
      showImage: false,
      shadow: 'shadow-none',
      hoverEffect: 'hover:border-l-4 hover:border-red-500 transition-colors duration-150',
    },
    page: {
      bgStyle: 'bg-neutral-200',
      fontFamily: 'font-mono',
      accentColor: 'neutral-800',
      borderRadius: 'rounded-none',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-neutral-800 text-white',
      position: 'bottom-right',
      shape: 'square',
    },
    dietBadge: { style: 'border' },
  },

  // ============================================================
  // MODERN / TRENDY DESIGNS (9-16)
  // ============================================================
  {
    id: 'modern-gradient',
    name: 'Gradient Wave',
    description: 'Vibrant purple-to-blue gradients with glassmorphism cards.',
    category: 'modern',
    preview: '🌊',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-br from-violet-600 to-blue-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-black/40 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-white/10 backdrop-blur-lg',
      activeStyle: 'bg-white text-violet-700',
      textColor: 'text-white/70',
      position: 'floating',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white/10 backdrop-blur-md',
      borderStyle: 'border border-white/20',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-white font-bold text-lg',
      nameStyle: 'text-white font-semibold',
      descStyle: 'text-white/60 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-violet-500/20',
      hoverEffect: 'hover:bg-white/20 hover:scale-[1.02] transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-gradient-to-b from-violet-600 via-blue-600 to-indigo-900',
      fontFamily: 'font-sans',
      accentColor: 'violet-400',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-white text-violet-700 shadow-lg shadow-violet-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'modern-neobrut',
    name: 'Neo Brutalist',
    description: 'Bold colors, thick borders, and chunky shadows in a playful style.',
    category: 'modern',
    preview: '🟡',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-yellow-300',
      textColor: 'text-black',
      logoSize: 'lg',
      showCover: false,
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-yellow-300',
      activeStyle: 'bg-black text-yellow-300 border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
      textColor: 'text-black',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
      imageStyle: 'square',
      imageSize: 'md',
      priceStyle: 'text-black font-black text-lg',
      nameStyle: 'text-black font-black text-base',
      descStyle: 'text-gray-600 text-sm',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-x-0.5 hover:-translate-y-0.5 transition-all duration-150',
    },
    page: {
      bgStyle: 'bg-yellow-300',
      fontFamily: 'font-sans',
      accentColor: 'yellow-400',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-black text-yellow-300 border-2 border-black shadow-[4px_4px_0px_0px_rgba(253,224,71,1)]',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'border' },
  },

  {
    id: 'modern-aurora',
    name: 'Aurora Borealis',
    description: 'Dark background with vivid teal-to-emerald aurora gradient accents.',
    category: 'modern',
    preview: '🌌',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gray-950',
      textColor: 'text-white',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-emerald-500/20 via-teal-500/10 to-gray-950',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-gray-900/80 backdrop-blur-lg',
      activeStyle: 'bg-gradient-to-r from-emerald-500 to-teal-400 text-white',
      textColor: 'text-gray-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-gray-900',
      borderStyle: 'border border-gray-800',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-emerald-400 font-bold',
      nameStyle: 'text-white font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-emerald-500/5',
      hoverEffect: 'hover:border-emerald-500/30 hover:shadow-emerald-500/10 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-gray-950',
      fontFamily: 'font-sans',
      accentColor: 'emerald-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-emerald-500 to-teal-400 text-white shadow-lg shadow-emerald-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'modern-coral',
    name: 'Coral Reef',
    description: 'Warm coral and peach with soft rounded cards and friendly vibes.',
    category: 'modern',
    preview: '🪸',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-br from-orange-400 to-rose-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-orange-500/30 to-transparent',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-orange-50',
      activeStyle: 'bg-orange-500 text-white shadow-md',
      textColor: 'text-orange-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-orange-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-orange-600 font-bold',
      nameStyle: 'text-gray-900 font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-orange-500/10',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-orange-50',
      fontFamily: 'font-sans',
      accentColor: 'orange-500',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-orange-500 to-rose-500 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'modern-midnight',
    name: 'Midnight Blue',
    description: 'Deep navy with electric blue highlights and sleek card design.',
    category: 'modern',
    preview: '🔵',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-blue-950',
      textColor: 'text-white',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-blue-900/50 to-blue-950',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-blue-950',
      activeStyle: 'border-b-2 border-blue-400 text-blue-400',
      textColor: 'text-blue-300/50',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-blue-900/50',
      borderStyle: 'border border-blue-800/50',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-blue-300 font-bold',
      nameStyle: 'text-white font-medium',
      descStyle: 'text-blue-300/60 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-blue-900/50',
      hoverEffect: 'hover:bg-blue-800/50 hover:border-blue-500/30 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-blue-950',
      fontFamily: 'font-sans',
      accentColor: 'blue-400',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-blue-500 text-white shadow-lg shadow-blue-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'modern-clay',
    name: 'Soft Clay',
    description: 'Claymorphism design with soft pastel backgrounds and pillowy shadows.',
    category: 'modern',
    preview: '🫧',
    header: {
      layout: 'centered',
      bgStyle: 'bg-indigo-100',
      textColor: 'text-indigo-900',
      logoSize: 'md',
      showCover: false,
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-indigo-100',
      activeStyle: 'bg-indigo-500 text-white shadow-md shadow-indigo-300/50',
      textColor: 'text-indigo-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-indigo-50',
      borderStyle: 'border border-indigo-200/50',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-indigo-600 font-bold',
      nameStyle: 'text-indigo-900 font-semibold',
      descStyle: 'text-indigo-400 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-indigo-200/50',
      hoverEffect: 'hover:shadow-xl hover:shadow-indigo-300/40 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-indigo-100',
      fontFamily: 'font-sans',
      accentColor: 'indigo-500',
      borderRadius: 'rounded-3xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-indigo-500 text-white shadow-lg shadow-indigo-400/40',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'modern-mesh',
    name: 'Mesh Gradient',
    description: 'Multi-color mesh gradient with glassmorphism overlays.',
    category: 'modern',
    preview: '🎨',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-br from-fuchsia-500 via-violet-600 to-cyan-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-black/20 backdrop-blur-sm',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-white/10 backdrop-blur-xl',
      activeStyle: 'bg-white/30 text-white border border-white/40',
      textColor: 'text-white/60',
      position: 'floating',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white/15 backdrop-blur-lg',
      borderStyle: 'border border-white/20',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-white font-bold',
      nameStyle: 'text-white font-semibold',
      descStyle: 'text-white/50 text-sm',
      showImage: true,
      shadow: 'shadow-xl shadow-black/10',
      hoverEffect: 'hover:bg-white/25 hover:scale-[1.03] transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-gradient-to-br from-fuchsia-600 via-violet-700 to-cyan-600',
      fontFamily: 'font-sans',
      accentColor: 'fuchsia-400',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-white/20 backdrop-blur-lg text-white border border-white/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'modern-retro-pop',
    name: 'Retro Pop',
    description: 'Retro 90s inspired with vivid lime-green, pink accents and bold type.',
    category: 'modern',
    preview: '🎯',
    header: {
      layout: 'split',
      bgStyle: 'bg-lime-400',
      textColor: 'text-black',
      logoSize: 'lg',
      showCover: true,
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-lime-400',
      activeStyle: 'bg-pink-500 text-white border-2 border-black',
      textColor: 'text-black',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border-2 border-black',
      imageStyle: 'circle',
      imageSize: 'md',
      priceStyle: 'text-pink-500 font-black text-lg',
      nameStyle: 'text-black font-black',
      descStyle: 'text-gray-600 text-sm',
      showImage: true,
      shadow: 'shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
      hoverEffect: 'hover:shadow-[5px_5px_0px_0px_rgba(236,72,153,1)] transition-all duration-150',
    },
    page: {
      bgStyle: 'bg-lime-400',
      fontFamily: 'font-sans',
      accentColor: 'pink-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-pink-500 text-white border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'border' },
  },

  // ============================================================
  // LUXURY / FINE DINING (17-22)
  // ============================================================
  {
    id: 'luxury-noir',
    name: 'Noir Elegance',
    description: 'Deep black with gold foil accents for ultimate sophistication.',
    category: 'luxury',
    preview: '✨',
    header: {
      layout: 'centered',
      bgStyle: 'bg-black',
      textColor: 'text-amber-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-black via-black/80 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-black',
      activeStyle: 'border-b border-amber-400 text-amber-300',
      textColor: 'text-gray-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-gray-950',
      borderStyle: 'border border-amber-900/30',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-amber-400 font-light text-lg tracking-wide',
      nameStyle: 'text-amber-100 font-light tracking-widest uppercase text-sm',
      descStyle: 'text-gray-500 text-sm italic',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:border-amber-700/50 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-black',
      fontFamily: 'font-serif',
      accentColor: 'amber-400',
      borderRadius: 'rounded-sm',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-amber-600 text-black',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'luxury-marble',
    name: 'White Marble',
    description: 'Pristine white with subtle gray veining textures and platinum accents.',
    category: 'luxury',
    preview: '🏛️',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gray-50',
      textColor: 'text-gray-800',
      logoSize: 'lg',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-gray-50',
      activeStyle: 'border-b-2 border-gray-400 text-gray-800',
      textColor: 'text-gray-300',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-white',
      borderStyle: 'border border-gray-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-gray-600 font-light text-lg',
      nameStyle: 'text-gray-800 font-light tracking-widest uppercase text-sm',
      descStyle: 'text-gray-400 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-300',
    },
    page: {
      bgStyle: 'bg-gray-50',
      fontFamily: 'font-serif',
      accentColor: 'gray-500',
      borderRadius: 'rounded-sm',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-gray-700 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'luxury-bordeaux',
    name: 'Bordeaux Wine',
    description: 'Rich burgundy and deep wine tones with cream text for fine dining.',
    category: 'luxury',
    preview: '🍷',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-red-950',
      textColor: 'text-amber-100',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-b from-red-950/70 to-red-950',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-red-950',
      activeStyle: 'border-b border-amber-300 text-amber-200',
      textColor: 'text-red-400/50',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-red-900/30',
      borderStyle: 'border border-red-800/30',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-amber-300 font-light text-lg',
      nameStyle: 'text-amber-100 font-light tracking-wider uppercase text-sm',
      descStyle: 'text-red-300/60 text-sm italic',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-red-900/50 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-red-950',
      fontFamily: 'font-serif',
      accentColor: 'amber-300',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-amber-600 text-red-950',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'luxury-champagne',
    name: 'Champagne Toast',
    description: 'Soft champagne gold on cream with refined typography.',
    category: 'fine-dining',
    preview: '🥂',
    header: {
      layout: 'centered',
      bgStyle: 'bg-yellow-50',
      textColor: 'text-yellow-900',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-b from-yellow-50/80 to-yellow-50',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-yellow-50',
      activeStyle: 'border-b border-yellow-700 text-yellow-800',
      textColor: 'text-yellow-400',
      position: 'inline',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border border-yellow-200',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-yellow-700 font-light text-lg',
      nameStyle: 'text-yellow-900 font-light tracking-wide',
      descStyle: 'text-yellow-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm shadow-yellow-200/50',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-yellow-50',
      fontFamily: 'font-serif',
      accentColor: 'yellow-700',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-yellow-700 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'luxury-emerald',
    name: 'Emerald Vault',
    description: 'Deep emerald green with gold details for an opulent feel.',
    category: 'luxury',
    preview: '💎',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-emerald-950',
      textColor: 'text-amber-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-emerald-950 via-emerald-950/80 to-transparent',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-emerald-950',
      activeStyle: 'bg-amber-600/20 text-amber-300 border-b border-amber-400',
      textColor: 'text-emerald-500/50',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-emerald-900/40',
      borderStyle: 'border border-emerald-800/40',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-amber-400 font-light text-lg',
      nameStyle: 'text-emerald-100 font-light tracking-wider uppercase text-sm',
      descStyle: 'text-emerald-400/50 text-sm',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:border-amber-700/30 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-emerald-950',
      fontFamily: 'font-serif',
      accentColor: 'amber-400',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-amber-500 text-emerald-950',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'luxury-platinum',
    name: 'Platinum Edge',
    description: 'Cool dark slate with silver metallic accents and sharp lines.',
    category: 'fine-dining',
    preview: '🪙',
    header: {
      layout: 'minimal-bar',
      bgStyle: 'bg-slate-900',
      textColor: 'text-slate-200',
      logoSize: 'md',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-slate-900',
      activeStyle: 'border-b border-slate-400 text-slate-200',
      textColor: 'text-slate-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'compact',
      bgStyle: 'bg-slate-800/50',
      borderStyle: 'border-b border-slate-700/50',
      imageStyle: 'none',
      imageSize: 'sm',
      priceStyle: 'text-slate-300 font-light text-lg tracking-wide',
      nameStyle: 'text-slate-100 font-light tracking-widest uppercase text-sm',
      descStyle: 'text-slate-500 text-xs italic',
      showImage: false,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-slate-800 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-slate-900',
      fontFamily: 'font-serif',
      accentColor: 'slate-300',
      borderRadius: 'rounded-none',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-slate-200 text-slate-900',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  // ============================================================
  // CASUAL / FAMILY RESTAURANT (23-28)
  // ============================================================
  {
    id: 'casual-sunny',
    name: 'Sunny Side Up',
    description: 'Bright yellow and warm orange with playful rounded cards for family dining.',
    category: 'casual',
    preview: '🌞',
    header: {
      layout: 'centered',
      bgStyle: 'bg-amber-400',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-b from-amber-400/50 to-amber-400',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-amber-50',
      activeStyle: 'bg-amber-500 text-white shadow-md',
      textColor: 'text-amber-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-amber-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-amber-600 font-bold text-lg',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-amber-50',
      fontFamily: 'font-sans',
      accentColor: 'amber-500',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-500 text-white shadow-lg shadow-amber-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'casual-garden',
    name: 'Green Garden',
    description: 'Fresh green palette with leafy vibes for health-conscious family spots.',
    category: 'casual',
    preview: '🥗',
    header: {
      layout: 'split',
      bgStyle: 'bg-green-600',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-green-50',
      activeStyle: 'bg-green-600 text-white',
      textColor: 'text-green-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border border-green-100',
      imageStyle: 'circle',
      imageSize: 'md',
      priceStyle: 'text-green-600 font-bold',
      nameStyle: 'text-gray-800 font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md hover:border-green-200 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-green-50',
      fontFamily: 'font-sans',
      accentColor: 'green-600',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-green-600 text-white shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'casual-retro-diner',
    name: 'Retro Diner',
    description: 'Classic American diner with red and cream checkerboard vibes.',
    category: 'casual',
    preview: '🍔',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-red-600',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-red-700',
      activeStyle: 'bg-yellow-400 text-red-800 font-bold',
      textColor: 'text-red-100',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-yellow-50',
      borderStyle: 'border-b-2 border-red-200',
      imageStyle: 'square',
      imageSize: 'md',
      priceStyle: 'text-red-600 font-bold text-lg',
      nameStyle: 'text-red-800 font-bold',
      descStyle: 'text-gray-600 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:bg-yellow-100 transition-colors duration-150',
    },
    page: {
      bgStyle: 'bg-yellow-50',
      fontFamily: 'font-sans',
      accentColor: 'red-600',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-red-600 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'casual-ocean',
    name: 'Ocean Breeze',
    description: 'Coastal blue and sandy beige for seafood and beach restaurants.',
    category: 'casual',
    preview: '🐚',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-b from-sky-400 to-sky-600',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-sky-600/50 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-sky-50',
      activeStyle: 'bg-sky-600 text-white',
      textColor: 'text-sky-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-sky-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-sky-600 font-bold',
      nameStyle: 'text-gray-800 font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-sky-100',
      hoverEffect: 'hover:shadow-lg transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-sky-50',
      fontFamily: 'font-sans',
      accentColor: 'sky-600',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-sky-600 text-white shadow-lg shadow-sky-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'casual-fiesta',
    name: 'Fiesta Fun',
    description: 'Multi-color festive palette with rounded cards and fun typography.',
    category: 'casual',
    preview: '🎉',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-black/20',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-purple-50',
      activeStyle: 'bg-purple-600 text-white shadow-md',
      textColor: 'text-purple-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white',
      borderStyle: 'border border-purple-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-purple-600 font-bold',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md',
      hoverEffect: 'hover:shadow-xl hover:scale-[1.02] transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-purple-50',
      fontFamily: 'font-sans',
      accentColor: 'purple-600',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-pink-500 to-purple-600 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'casual-rustic',
    name: 'Rustic Table',
    description: 'Earthy brown and cream with a warm farmhouse dining feel.',
    category: 'casual',
    preview: '🪵',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-amber-900',
      textColor: 'text-amber-100',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-r from-amber-900/80 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-amber-100',
      activeStyle: 'border-b-2 border-amber-800 text-amber-900',
      textColor: 'text-amber-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-amber-50',
      borderStyle: 'border border-amber-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-amber-800 font-bold',
      nameStyle: 'text-amber-900 font-semibold',
      descStyle: 'text-amber-700/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:bg-amber-100 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-amber-100',
      fontFamily: 'font-serif',
      accentColor: 'amber-800',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-800 text-white',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  // ============================================================
  // ETHNIC / CULTURAL (29-34)
  // ============================================================
  {
    id: 'ethnic-indian',
    name: 'Royal Spice',
    description: 'Rich saffron, deep maroon, and gold for Indian cuisine ambiance.',
    category: 'ethnic',
    preview: '🪷',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-br from-orange-700 via-red-800 to-amber-900',
      textColor: 'text-amber-100',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-red-900/80 to-transparent',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-orange-50',
      activeStyle: 'bg-red-800 text-amber-100',
      textColor: 'text-red-800',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-orange-50',
      borderStyle: 'border border-orange-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-red-700 font-bold',
      nameStyle: 'text-red-900 font-semibold',
      descStyle: 'text-orange-700/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md hover:border-amber-400 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-orange-50',
      fontFamily: 'font-serif',
      accentColor: 'red-800',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-red-800 text-amber-100 shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'ethnic-japanese',
    name: 'Zen Garden',
    description: 'Minimal Japanese aesthetic with slate, cream, and subtle red accents.',
    category: 'ethnic',
    preview: '🏯',
    header: {
      layout: 'minimal-bar',
      bgStyle: 'bg-stone-100',
      textColor: 'text-stone-800',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-stone-100',
      activeStyle: 'border-b-2 border-red-600 text-stone-800',
      textColor: 'text-stone-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border-b border-stone-200',
      imageStyle: 'square',
      imageSize: 'md',
      priceStyle: 'text-red-600 font-medium',
      nameStyle: 'text-stone-800 font-medium',
      descStyle: 'text-stone-400 text-sm',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-stone-50 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-stone-100',
      fontFamily: 'font-sans',
      accentColor: 'red-600',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-red-600 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'ethnic-italian',
    name: 'Trattoria',
    description: 'Warm terracotta and olive green evoking an Italian countryside dining.',
    category: 'ethnic',
    preview: '🇮🇹',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-b from-green-800 to-green-900',
      textColor: 'text-amber-100',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-green-900/80 to-transparent',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-green-50',
      activeStyle: 'bg-green-800 text-white',
      textColor: 'text-green-800',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-green-50',
      borderStyle: 'border border-green-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-green-800 font-semibold',
      nameStyle: 'text-green-900 font-semibold italic',
      descStyle: 'text-green-700/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-amber-50',
      fontFamily: 'font-serif',
      accentColor: 'green-800',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-green-800 text-white',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'ethnic-mexican',
    name: 'Cantina Caliente',
    description: 'Vibrant terracotta, teal, and warm yellow for Mexican cantina vibes.',
    category: 'ethnic',
    preview: '🌮',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-br from-orange-600 to-red-700',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-black/30',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-orange-50',
      activeStyle: 'bg-teal-600 text-white',
      textColor: 'text-orange-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border-l-4 border-teal-500',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-orange-600 font-bold',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:border-l-4 hover:border-orange-500 transition-colors duration-150',
    },
    page: {
      bgStyle: 'bg-orange-50',
      fontFamily: 'font-sans',
      accentColor: 'teal-600',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-teal-600 text-white shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'ethnic-thai',
    name: 'Golden Temple',
    description: 'Warm gold and purple inspired by Thai temple aesthetics.',
    category: 'ethnic',
    preview: '🛕',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-b from-purple-900 to-purple-950',
      textColor: 'text-yellow-300',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-purple-950/80 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-purple-50',
      activeStyle: 'bg-purple-800 text-yellow-300',
      textColor: 'text-purple-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-purple-50',
      borderStyle: 'border border-purple-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-purple-800 font-bold',
      nameStyle: 'text-purple-900 font-semibold',
      descStyle: 'text-purple-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md hover:border-yellow-400 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-purple-50',
      fontFamily: 'font-sans',
      accentColor: 'purple-800',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-purple-800 text-yellow-300 shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'ethnic-chinese',
    name: 'Red Lantern',
    description: 'Classic red and gold Chinese restaurant palette with elegant accents.',
    category: 'ethnic',
    preview: '🏮',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-red-800',
      textColor: 'text-yellow-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-b from-red-800/50 to-red-900',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-red-50',
      activeStyle: 'bg-red-700 text-yellow-200',
      textColor: 'text-red-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-red-50',
      borderStyle: 'border border-red-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-red-700 font-bold',
      nameStyle: 'text-red-900 font-semibold',
      descStyle: 'text-red-600/50 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md hover:border-yellow-400 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-red-50',
      fontFamily: 'font-serif',
      accentColor: 'red-700',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-red-700 text-yellow-200 shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  // ============================================================
  // CAFE / COFFEE SHOP (35-40)
  // ============================================================
  {
    id: 'cafe-espresso',
    name: 'Espresso Bar',
    description: 'Rich dark brown and cream for a classic espresso bar aesthetic.',
    category: 'cafe',
    preview: '☕',
    header: {
      layout: 'centered',
      bgStyle: 'bg-amber-950',
      textColor: 'text-amber-100',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-amber-950/90 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-amber-100',
      activeStyle: 'bg-amber-900 text-amber-100',
      textColor: 'text-amber-800',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-amber-50',
      borderStyle: 'border border-amber-200',
      imageStyle: 'circle',
      imageSize: 'md',
      priceStyle: 'text-amber-900 font-bold',
      nameStyle: 'text-amber-950 font-semibold',
      descStyle: 'text-amber-700/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-amber-100',
      fontFamily: 'font-serif',
      accentColor: 'amber-900',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-900 text-amber-100 shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'cafe-scandinavian',
    name: 'Nordic Fika',
    description: 'Light wood tones with soft gray and warm white for Scandinavian simplicity.',
    category: 'cafe',
    preview: '🫖',
    header: {
      layout: 'minimal-bar',
      bgStyle: 'bg-stone-50',
      textColor: 'text-stone-700',
      logoSize: 'sm',
      showCover: false,
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-stone-50',
      activeStyle: 'border-b-2 border-stone-500 text-stone-700',
      textColor: 'text-stone-300',
      position: 'inline',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-stone-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-stone-600 font-medium',
      nameStyle: 'text-stone-700 font-medium',
      descStyle: 'text-stone-400 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-stone-50',
      fontFamily: 'font-sans',
      accentColor: 'stone-600',
      borderRadius: 'rounded-xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-stone-600 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'cafe-matcha',
    name: 'Matcha House',
    description: 'Soft matcha green and cream with a serene Japanese cafe feel.',
    category: 'cafe',
    preview: '🍵',
    header: {
      layout: 'centered',
      bgStyle: 'bg-green-800',
      textColor: 'text-green-50',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-green-800/60 to-green-800',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-green-50',
      activeStyle: 'bg-green-700 text-white',
      textColor: 'text-green-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-green-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-green-700 font-semibold',
      nameStyle: 'text-green-900 font-medium',
      descStyle: 'text-green-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm shadow-green-100',
      hoverEffect: 'hover:shadow-md hover:shadow-green-200 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-green-50',
      fontFamily: 'font-sans',
      accentColor: 'green-700',
      borderRadius: 'rounded-2xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-green-700 text-white shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'cafe-parisian',
    name: 'Parisian Bistro',
    description: 'Navy blue and gold with classic French bistro charm.',
    category: 'cafe',
    preview: '🥐',
    header: {
      layout: 'centered',
      bgStyle: 'bg-blue-900',
      textColor: 'text-amber-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-blue-900/90 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-blue-50',
      activeStyle: 'border-b-2 border-blue-800 text-blue-900',
      textColor: 'text-blue-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-blue-50',
      borderStyle: 'border border-blue-100',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-blue-800 font-semibold',
      nameStyle: 'text-blue-900 font-semibold italic',
      descStyle: 'text-blue-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:bg-white transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-blue-50',
      fontFamily: 'font-serif',
      accentColor: 'blue-900',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-blue-900 text-amber-200',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'cafe-tropical',
    name: 'Tropical Juice Bar',
    description: 'Bright tropical colors with playful pink and turquoise for smoothie bars.',
    category: 'cafe',
    preview: '🥤',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-br from-pink-400 to-teal-400',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-black/10',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-teal-50',
      activeStyle: 'bg-pink-500 text-white shadow-md',
      textColor: 'text-teal-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white',
      borderStyle: 'border border-teal-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-pink-500 font-bold',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-teal-50',
      fontFamily: 'font-sans',
      accentColor: 'pink-500',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-pink-500 to-teal-500 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'cafe-bookshop',
    name: 'Bookshop Cafe',
    description: 'Warm brown leather and cream with a cozy literary atmosphere.',
    category: 'cafe',
    preview: '📚',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-yellow-900',
      textColor: 'text-yellow-100',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-r from-yellow-900/90 to-transparent',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-yellow-50',
      activeStyle: 'bg-yellow-900 text-yellow-100',
      textColor: 'text-yellow-800',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'compact',
      bgStyle: 'bg-yellow-50',
      borderStyle: 'border-b border-yellow-200',
      imageStyle: 'none',
      imageSize: 'sm',
      priceStyle: 'text-yellow-800 font-semibold',
      nameStyle: 'text-yellow-900 font-medium',
      descStyle: 'text-yellow-700/60 text-sm italic',
      showImage: false,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-yellow-100 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-yellow-50',
      fontFamily: 'font-serif',
      accentColor: 'yellow-900',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-yellow-900 text-yellow-100',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  // ============================================================
  // FAST FOOD / QUICK SERVICE (41-46)
  // ============================================================
  {
    id: 'fastfood-bold',
    name: 'Bold Bites',
    description: 'High-contrast red and yellow with large images for fast food appeal.',
    category: 'fast-food',
    preview: '🍟',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-red-600',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-red-600 to-transparent',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-yellow-400',
      activeStyle: 'bg-red-600 text-white shadow-md',
      textColor: 'text-red-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white',
      borderStyle: 'border-none',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-red-600 font-black text-lg',
      nameStyle: 'text-gray-900 font-black',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-lg',
      hoverEffect: 'hover:shadow-xl hover:scale-[1.03] transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-gray-100',
      fontFamily: 'font-sans',
      accentColor: 'red-600',
      borderRadius: 'rounded-xl',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-red-600 text-white shadow-xl shadow-red-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'fastfood-neon-green',
    name: 'Neon Crunch',
    description: 'Electric green on dark for a trendy fast-casual health food vibe.',
    category: 'fast-food',
    preview: '🥦',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-gray-900',
      textColor: 'text-lime-400',
      logoSize: 'lg',
      showCover: false,
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-gray-900',
      activeStyle: 'bg-lime-500 text-gray-900',
      textColor: 'text-gray-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-gray-800',
      borderStyle: 'border border-gray-700',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-lime-400 font-bold text-lg',
      nameStyle: 'text-white font-bold',
      descStyle: 'text-gray-400 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-black/30',
      hoverEffect: 'hover:border-lime-500/50 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-gray-900',
      fontFamily: 'font-sans',
      accentColor: 'lime-500',
      borderRadius: 'rounded-xl',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-lime-500 text-gray-900 font-bold shadow-lg shadow-lime-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'fastfood-orange',
    name: 'Orange Burst',
    description: 'Bright orange with white cards for energetic quick-service restaurants.',
    category: 'fast-food',
    preview: '🍊',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-orange-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-orange-600 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-white',
      activeStyle: 'bg-orange-500 text-white',
      textColor: 'text-orange-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border-none',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-orange-600 font-bold text-lg',
      nameStyle: 'text-gray-900 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md',
      hoverEffect: 'hover:shadow-xl transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-orange-50',
      fontFamily: 'font-sans',
      accentColor: 'orange-500',
      borderRadius: 'rounded-2xl',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-orange-500 text-white shadow-lg shadow-orange-500/40',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'fastfood-pizza',
    name: 'Pizza Express',
    description: 'Warm red and golden yellow with bold type for pizza and delivery menus.',
    category: 'fast-food',
    preview: '🍕',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-br from-red-700 to-yellow-600',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-black/20',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-red-50',
      activeStyle: 'bg-red-600 text-white',
      textColor: 'text-red-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-white',
      borderStyle: 'border border-red-100',
      imageStyle: 'square',
      imageSize: 'lg',
      priceStyle: 'text-red-600 font-black text-lg',
      nameStyle: 'text-gray-900 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md',
      hoverEffect: 'hover:shadow-lg transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-red-50',
      fontFamily: 'font-sans',
      accentColor: 'red-600',
      borderRadius: 'rounded-xl',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-red-600 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'fastfood-street',
    name: 'Street Eats',
    description: 'Urban gray and yellow with a gritty street food market feel.',
    category: 'fast-food',
    preview: '🛒',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-zinc-900',
      textColor: 'text-yellow-400',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-r from-zinc-900/90 to-transparent',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-zinc-800',
      activeStyle: 'bg-yellow-400 text-zinc-900',
      textColor: 'text-zinc-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-zinc-800',
      borderStyle: 'border border-zinc-700',
      imageStyle: 'square',
      imageSize: 'md',
      priceStyle: 'text-yellow-400 font-bold',
      nameStyle: 'text-white font-bold',
      descStyle: 'text-zinc-400 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-black/30',
      hoverEffect: 'hover:border-yellow-400/50 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-zinc-900',
      fontFamily: 'font-sans',
      accentColor: 'yellow-400',
      borderRadius: 'rounded-lg',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-yellow-400 text-zinc-900 font-bold shadow-lg',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'border' },
  },

  {
    id: 'fastfood-bubblegum',
    name: 'Bubblegum Pop',
    description: 'Playful pink and blue pastels for kids menus and dessert quick-serve.',
    category: 'fast-food',
    preview: '🍬',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-r from-pink-400 to-blue-400',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-white/10',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-pink-50',
      activeStyle: 'bg-pink-500 text-white shadow-md',
      textColor: 'text-pink-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white',
      borderStyle: 'border-2 border-pink-200',
      imageStyle: 'circle',
      imageSize: 'lg',
      priceStyle: 'text-pink-500 font-black text-lg',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-pink-200/50',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-pink-50',
      fontFamily: 'font-sans',
      accentColor: 'pink-500',
      borderRadius: 'rounded-3xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-pink-500 to-blue-500 text-white shadow-lg',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  // ============================================================
  // BAR / LOUNGE / PUB (47-52)
  // ============================================================
  {
    id: 'bar-speakeasy',
    name: 'Speakeasy',
    description: 'Art deco inspired dark palette with amber and brass accents.',
    category: 'bar',
    preview: '🥃',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-zinc-950',
      textColor: 'text-amber-300',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-zinc-950 via-zinc-950/80 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-zinc-950',
      activeStyle: 'border-b border-amber-500 text-amber-400',
      textColor: 'text-zinc-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-zinc-900',
      borderStyle: 'border border-amber-900/30',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-amber-400 font-medium',
      nameStyle: 'text-amber-200 font-light tracking-wider uppercase text-sm',
      descStyle: 'text-zinc-500 text-sm italic',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:border-amber-700/50 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-zinc-950',
      fontFamily: 'font-serif',
      accentColor: 'amber-500',
      borderRadius: 'rounded-sm',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-amber-600 text-zinc-950',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'bar-rooftop',
    name: 'Rooftop Lounge',
    description: 'Deep blue night sky tones with soft purple and city-light accents.',
    category: 'bar',
    preview: '🌃',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gradient-to-b from-indigo-900 to-slate-900',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-slate-900/80 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-slate-900/80 backdrop-blur-md',
      activeStyle: 'bg-purple-500 text-white',
      textColor: 'text-slate-400',
      position: 'floating',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-slate-800/50 backdrop-blur-sm',
      borderStyle: 'border border-slate-700/50',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-purple-400 font-semibold',
      nameStyle: 'text-white font-medium',
      descStyle: 'text-slate-400 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-black/20',
      hoverEffect: 'hover:bg-slate-700/50 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-slate-900',
      fontFamily: 'font-sans',
      accentColor: 'purple-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-purple-500 text-white shadow-lg shadow-purple-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'bar-irish-pub',
    name: 'Irish Pub',
    description: 'Dark wood and emerald green with a cozy traditional pub atmosphere.',
    category: 'bar',
    preview: '🍺',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-green-950',
      textColor: 'text-amber-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-r from-green-950/90 to-transparent',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-green-900',
      activeStyle: 'bg-amber-600 text-white',
      textColor: 'text-green-300',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-green-900/50',
      borderStyle: 'border border-green-800/50',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-amber-400 font-bold',
      nameStyle: 'text-green-100 font-semibold',
      descStyle: 'text-green-300/60 text-sm',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-green-800/50 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-green-950',
      fontFamily: 'font-serif',
      accentColor: 'amber-500',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-600 text-white',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'bar-wine-bar',
    name: 'Wine Cellar',
    description: 'Deep burgundy and ivory for an intimate wine bar ambiance.',
    category: 'bar',
    preview: '🍇',
    header: {
      layout: 'centered',
      bgStyle: 'bg-rose-950',
      textColor: 'text-rose-100',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-rose-950 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-rose-950',
      activeStyle: 'border-b border-rose-300 text-rose-200',
      textColor: 'text-rose-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'detailed',
      bgStyle: 'bg-rose-900/30',
      borderStyle: 'border border-rose-800/30',
      imageStyle: 'rounded',
      imageSize: 'sm',
      priceStyle: 'text-rose-300 font-light text-lg',
      nameStyle: 'text-rose-100 font-light tracking-wide',
      descStyle: 'text-rose-400/50 text-sm italic',
      showImage: true,
      shadow: 'shadow-none',
      hoverEffect: 'hover:bg-rose-900/50 transition-colors duration-300',
    },
    page: {
      bgStyle: 'bg-rose-950',
      fontFamily: 'font-serif',
      accentColor: 'rose-300',
      borderRadius: 'rounded-lg',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-rose-600 text-white',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'bar-cocktail',
    name: 'Cocktail Lab',
    description: 'Sleek dark with vibrant cyan accents for a modern cocktail bar.',
    category: 'bar',
    preview: '🍸',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-gray-950',
      textColor: 'text-cyan-300',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-t from-gray-950 via-gray-950/70 to-transparent',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-gray-900',
      activeStyle: 'bg-cyan-500 text-gray-950',
      textColor: 'text-gray-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-gray-900',
      borderStyle: 'border border-gray-800',
      imageStyle: 'circle',
      imageSize: 'md',
      priceStyle: 'text-cyan-400 font-bold',
      nameStyle: 'text-white font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-cyan-500/5',
      hoverEffect: 'hover:border-cyan-500/30 hover:shadow-cyan-500/10 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-gray-950',
      fontFamily: 'font-sans',
      accentColor: 'cyan-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-cyan-500 text-gray-950 shadow-lg shadow-cyan-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'bar-sports',
    name: 'Sports Bar',
    description: 'Bold dark green and white with energetic typography for sports bars.',
    category: 'bar',
    preview: '🏈',
    header: {
      layout: 'left-aligned',
      bgStyle: 'bg-green-800',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-r from-green-900/80 to-transparent',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-green-800',
      activeStyle: 'bg-white text-green-800',
      textColor: 'text-green-200',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-green-900/50',
      borderStyle: 'border border-green-700',
      imageStyle: 'square',
      imageSize: 'md',
      priceStyle: 'text-green-300 font-bold text-lg',
      nameStyle: 'text-white font-bold uppercase',
      descStyle: 'text-green-300/60 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-black/20',
      hoverEffect: 'hover:bg-green-800 transition-colors duration-200',
    },
    page: {
      bgStyle: 'bg-green-900',
      fontFamily: 'font-sans',
      accentColor: 'green-400',
      borderRadius: 'rounded-lg',
      spacing: 'compact',
    },
    cartButton: {
      style: 'bg-white text-green-800 font-bold shadow-lg',
      position: 'bottom-center',
      shape: 'rounded',
    },
    dietBadge: { style: 'tag' },
  },

  // ============================================================
  // BAKERY / DESSERT (53-58)
  // ============================================================
  {
    id: 'bakery-pastel',
    name: 'Pastel Patisserie',
    description: 'Soft pastel lavender and cream with delicate rounded cards.',
    category: 'bakery',
    preview: '🧁',
    header: {
      layout: 'centered',
      bgStyle: 'bg-violet-100',
      textColor: 'text-violet-900',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-b from-violet-100/80 to-violet-100',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-violet-50',
      activeStyle: 'bg-violet-500 text-white',
      textColor: 'text-violet-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-violet-100',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-violet-600 font-semibold',
      nameStyle: 'text-violet-900 font-semibold',
      descStyle: 'text-violet-400 text-sm',
      showImage: true,
      shadow: 'shadow-sm shadow-violet-100',
      hoverEffect: 'hover:shadow-md hover:shadow-violet-200 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-violet-50',
      fontFamily: 'font-serif',
      accentColor: 'violet-500',
      borderRadius: 'rounded-2xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-violet-500 text-white shadow-md shadow-violet-300/50',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'bakery-chocolate',
    name: 'Chocolate Box',
    description: 'Rich chocolate brown with warm highlights for premium bakeries.',
    category: 'bakery',
    preview: '🍫',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-amber-950',
      textColor: 'text-orange-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-amber-950 via-amber-950/70 to-transparent',
    },
    categoryNav: {
      style: 'tabs',
      bgStyle: 'bg-orange-50',
      activeStyle: 'bg-amber-800 text-orange-100',
      textColor: 'text-amber-800',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-orange-50',
      borderStyle: 'border border-amber-200',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-amber-800 font-bold',
      nameStyle: 'text-amber-950 font-semibold',
      descStyle: 'text-amber-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-amber-200/50',
      hoverEffect: 'hover:shadow-lg transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-orange-50',
      fontFamily: 'font-serif',
      accentColor: 'amber-800',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-amber-800 text-orange-100 shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'bakery-strawberry',
    name: 'Strawberry Fields',
    description: 'Soft pink and red with playful berry-inspired card design.',
    category: 'bakery',
    preview: '🍓',
    header: {
      layout: 'centered',
      bgStyle: 'bg-gradient-to-b from-red-400 to-pink-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-white/10',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-pink-50',
      activeStyle: 'bg-red-500 text-white shadow-md',
      textColor: 'text-red-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-pink-100',
      imageStyle: 'circle',
      imageSize: 'lg',
      priceStyle: 'text-red-500 font-bold',
      nameStyle: 'text-gray-800 font-bold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-pink-100',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-pink-50',
      fontFamily: 'font-sans',
      accentColor: 'red-500',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-red-500 text-white shadow-lg shadow-red-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'bakery-french',
    name: 'French Boulangerie',
    description: 'Classic French navy and gold with serif typography for artisan bakeries.',
    category: 'bakery',
    preview: '🥖',
    header: {
      layout: 'centered',
      bgStyle: 'bg-blue-950',
      textColor: 'text-amber-200',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-blue-950/90 to-transparent',
    },
    categoryNav: {
      style: 'underline',
      bgStyle: 'bg-amber-50',
      activeStyle: 'border-b-2 border-blue-900 text-blue-900',
      textColor: 'text-blue-400',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-amber-50',
      borderStyle: 'border border-amber-200',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-blue-900 font-semibold',
      nameStyle: 'text-blue-950 font-semibold italic',
      descStyle: 'text-blue-800/50 text-sm',
      showImage: true,
      shadow: 'shadow-sm',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-amber-50',
      fontFamily: 'font-serif',
      accentColor: 'blue-950',
      borderRadius: 'rounded-lg',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-blue-950 text-amber-200',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'tag' },
  },

  {
    id: 'bakery-vanilla',
    name: 'Vanilla Dream',
    description: 'Warm vanilla cream and soft gold for an inviting dessert shop.',
    category: 'bakery',
    preview: '🍦',
    header: {
      layout: 'centered',
      bgStyle: 'bg-yellow-100',
      textColor: 'text-yellow-900',
      logoSize: 'md',
      showCover: true,
      overlay: 'bg-gradient-to-b from-yellow-100/80 to-yellow-100',
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-yellow-50',
      activeStyle: 'bg-yellow-600 text-white',
      textColor: 'text-yellow-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'grid-square',
      bgStyle: 'bg-white',
      borderStyle: 'border border-yellow-200',
      imageStyle: 'rounded',
      imageSize: 'lg',
      priceStyle: 'text-yellow-700 font-semibold',
      nameStyle: 'text-yellow-900 font-medium',
      descStyle: 'text-yellow-600/60 text-sm',
      showImage: true,
      shadow: 'shadow-sm shadow-yellow-200/50',
      hoverEffect: 'hover:shadow-md transition-shadow duration-200',
    },
    page: {
      bgStyle: 'bg-yellow-50',
      fontFamily: 'font-sans',
      accentColor: 'yellow-600',
      borderRadius: 'rounded-2xl',
      spacing: 'spacious',
    },
    cartButton: {
      style: 'bg-yellow-600 text-white shadow-md',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  {
    id: 'bakery-mint',
    name: 'Mint Gelato',
    description: 'Cool mint green and white for an ice cream and gelato shop feel.',
    category: 'bakery',
    preview: '🍨',
    header: {
      layout: 'centered',
      bgStyle: 'bg-emerald-500',
      textColor: 'text-white',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-emerald-600/50 to-transparent',
    },
    categoryNav: {
      style: 'scroll-cards',
      bgStyle: 'bg-emerald-50',
      activeStyle: 'bg-emerald-600 text-white shadow-md',
      textColor: 'text-emerald-700',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'vertical',
      bgStyle: 'bg-white',
      borderStyle: 'border border-emerald-100',
      imageStyle: 'circle',
      imageSize: 'lg',
      priceStyle: 'text-emerald-600 font-bold',
      nameStyle: 'text-gray-800 font-semibold',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-emerald-100',
      hoverEffect: 'hover:shadow-lg hover:-translate-y-1 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-emerald-50',
      fontFamily: 'font-sans',
      accentColor: 'emerald-600',
      borderRadius: 'rounded-2xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-emerald-600 text-white shadow-lg shadow-emerald-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'icon' },
  },

  // ============================================================
  // SPECIAL (59-60)
  // ============================================================
  {
    id: 'special-dark-mode',
    name: 'Midnight Mode',
    description: 'Full dark mode with subtle gray hierarchy and blue-purple accents.',
    category: 'modern',
    preview: '🌙',
    header: {
      layout: 'minimal-bar',
      bgStyle: 'bg-gray-950',
      textColor: 'text-gray-100',
      logoSize: 'md',
      showCover: false,
    },
    categoryNav: {
      style: 'pills',
      bgStyle: 'bg-gray-900',
      activeStyle: 'bg-blue-600 text-white',
      textColor: 'text-gray-500',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-gray-900',
      borderStyle: 'border border-gray-800',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-blue-400 font-bold',
      nameStyle: 'text-gray-100 font-medium',
      descStyle: 'text-gray-500 text-sm',
      showImage: true,
      shadow: 'shadow-md shadow-black/30',
      hoverEffect: 'hover:bg-gray-800 hover:border-gray-700 transition-all duration-200',
    },
    page: {
      bgStyle: 'bg-gray-950',
      fontFamily: 'font-sans',
      accentColor: 'blue-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-blue-600 text-white shadow-lg shadow-blue-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },

  {
    id: 'special-neon',
    name: 'Neon Nights',
    description: 'Electric neon pink and cyan on pure black for a vibrant nightlife menu.',
    category: 'bar',
    preview: '💜',
    header: {
      layout: 'overlay',
      bgStyle: 'bg-black',
      textColor: 'text-fuchsia-400',
      logoSize: 'lg',
      showCover: true,
      overlay: 'bg-gradient-to-t from-black via-black/90 to-fuchsia-900/20',
    },
    categoryNav: {
      style: 'chips',
      bgStyle: 'bg-black',
      activeStyle: 'bg-fuchsia-500 text-white shadow-lg shadow-fuchsia-500/30',
      textColor: 'text-gray-600',
      position: 'sticky-top',
    },
    itemCard: {
      layout: 'horizontal',
      bgStyle: 'bg-gray-950',
      borderStyle: 'border border-fuchsia-500/20',
      imageStyle: 'rounded',
      imageSize: 'md',
      priceStyle: 'text-cyan-400 font-bold text-lg',
      nameStyle: 'text-fuchsia-300 font-bold',
      descStyle: 'text-gray-600 text-sm',
      showImage: true,
      shadow: 'shadow-lg shadow-fuchsia-500/5',
      hoverEffect: 'hover:border-fuchsia-500/50 hover:shadow-fuchsia-500/20 transition-all duration-300',
    },
    page: {
      bgStyle: 'bg-black',
      fontFamily: 'font-sans',
      accentColor: 'fuchsia-500',
      borderRadius: 'rounded-xl',
      spacing: 'normal',
    },
    cartButton: {
      style: 'bg-gradient-to-r from-fuchsia-500 to-cyan-400 text-white shadow-xl shadow-fuchsia-500/30',
      position: 'bottom-center',
      shape: 'pill',
    },
    dietBadge: { style: 'dot' },
  },
];

export const getMenuTemplateById = (id: string): MenuTemplateConfig | undefined =>
  menuTemplateConfigs.find((t) => t.id === id);

export const getMenuTemplatesByCategory = (
  category: MenuTemplateConfig['category']
): MenuTemplateConfig[] => menuTemplateConfigs.filter((t) => t.category === category);
