/**
 * Pre-designed starter content for each template.
 * When user picks a template, this fills in demo content they can edit.
 */
import type { MiniSiteCreatePayload } from '@/types/minisite';

type PresetContent = Omit<MiniSiteCreatePayload, 'template_id' | 'custom_colors' | 'custom_fonts'>;

const presets: Record<string, PresetContent> = {
  'gradient-startup': {
    site_name: 'LaunchPad',
    tagline: 'Ship faster, grow smarter',
    logo_url: null,
    favicon_url: null,
    hero_title: 'Build Products That Users Love',
    hero_subtitle: 'The all-in-one platform to launch, grow, and scale your startup. Join 10,000+ founders who trust LaunchPad.',
    hero_image_url: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop',
    hero_cta_text: 'Start Free Trial',
    hero_cta_url: '#',
    about_title: 'Why Choose LaunchPad?',
    about_text: 'We help startups go from idea to product in weeks, not months. Our platform provides everything you need — from landing pages to analytics — so you can focus on what matters most: your customers.',
    about_image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=400&fit=crop',
    features: [
      { title: 'Lightning Fast', icon: '⚡', description: 'Deploy in seconds with our optimized infrastructure' },
      { title: 'Secure by Default', icon: '🔒', description: 'Enterprise-grade security with SOC2 compliance' },
      { title: 'Analytics Built-In', icon: '📊', description: 'Track every metric that matters to your growth' },
    ],
    testimonials: [
      { name: 'Sarah Chen', text: 'LaunchPad helped us go from zero to 10K users in 3 months. Incredible platform!', role: 'CEO, TechFlow' },
      { name: 'James Wilson', text: 'The best investment we made for our startup. Simple, fast, powerful.', role: 'Founder, DataSync' },
    ],
    gallery: [],
    cta_title: 'Ready to Launch Your Next Big Idea?',
    cta_subtitle: 'Join thousands of founders building the future.',
    cta_button_text: 'Get Started Free',
    cta_button_url: '#',
    phone: '+1 (555) 123-4567',
    email: 'hello@launchpad.io',
    address: null,
    whatsapp: null,
    website: 'https://launchpad.io',
    linkedin: 'https://linkedin.com',
    instagram: null,
    github: null,
    twitter: 'https://twitter.com',
    youtube: null,
    footer_text: null,
  },
  'minimal-portfolio': {
    site_name: 'Alex Morgan',
    tagline: 'Digital Designer & Creative Director',
    logo_url: null, favicon_url: null,
    hero_title: 'Crafting Digital Experiences That Inspire',
    hero_subtitle: 'I design clean, user-centered interfaces for brands that want to stand out.',
    hero_image_url: null,
    hero_cta_text: 'View My Work', hero_cta_url: '#',
    about_title: 'About Me',
    about_text: 'With 8+ years in digital design, I help brands create meaningful connections through thoughtful UI/UX. My work spans web, mobile, and brand identity.',
    about_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
    features: [
      { title: 'UI/UX Design', icon: '🎨', description: 'User-centered interfaces that convert' },
      { title: 'Brand Identity', icon: '✦', description: 'Logos, typography, and visual systems' },
      { title: 'Web Development', icon: '💻', description: 'Clean code, responsive, fast' },
    ],
    testimonials: [{ name: 'Nike Creative Team', text: 'Alex transformed our digital presence. Truly world-class design.', role: 'Brand Partner' }],
    gallery: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=500&fit=crop', 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=500&h=500&fit=crop', 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=500&h=500&fit=crop'],
    cta_title: 'Let\'s Create Something Beautiful',
    cta_subtitle: null, cta_button_text: 'Get In Touch', cta_button_url: '#',
    phone: null, email: 'alex@design.co', address: null, whatsapp: null,
    website: null, linkedin: 'https://linkedin.com', instagram: 'https://instagram.com', github: null, twitter: null, youtube: null, footer_text: null,
  },
  'dark-saas': {
    site_name: 'CloudSync',
    tagline: 'Enterprise Cloud Infrastructure',
    logo_url: null, favicon_url: null,
    hero_title: 'Infrastructure That Scales With You',
    hero_subtitle: 'Deploy, manage, and monitor your applications with enterprise-grade reliability. 99.99% uptime guaranteed.',
    hero_image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=500&fit=crop',
    hero_cta_text: 'Start Building', hero_cta_url: '#',
    about_title: 'Trusted by Industry Leaders',
    about_text: 'From startups to Fortune 500 companies, CloudSync powers the most demanding applications. Our global edge network ensures your users get blazing-fast experiences anywhere in the world.',
    about_image_url: null,
    features: [
      { title: 'Global CDN', icon: '🌍', description: '200+ edge locations worldwide' },
      { title: 'Auto Scaling', icon: '📈', description: 'Handles any traffic spike seamlessly' },
      { title: 'Real-time Monitoring', icon: '📡', description: 'Full observability with custom dashboards' },
      { title: 'One-Click Deploy', icon: '🚀', description: 'Push to production in seconds' },
    ],
    testimonials: [
      { name: 'CTO, Stripe', text: 'CloudSync reduced our infrastructure costs by 40% while improving performance.', role: 'Engineering' },
      { name: 'VP Eng, Shopify', text: 'The most reliable cloud platform we\'ve ever used. Period.', role: 'Platform Team' },
    ],
    gallery: [], cta_title: 'Start Building Today', cta_subtitle: 'Free tier includes 100GB bandwidth. No credit card required.',
    cta_button_text: 'Deploy Now', cta_button_url: '#',
    phone: null, email: 'sales@cloudsync.io', address: 'San Francisco, CA', whatsapp: null,
    website: null, linkedin: 'https://linkedin.com', instagram: null, github: 'https://github.com', twitter: 'https://twitter.com', youtube: null, footer_text: null,
  },
  'restaurant-elegant': {
    site_name: 'La Maison',
    tagline: 'Fine Dining Experience Since 1985',
    logo_url: null, favicon_url: null,
    hero_title: 'Where Every Meal Becomes a Memory',
    hero_subtitle: 'Experience exquisite French-Italian cuisine crafted by award-winning Chef Marco Bellini.',
    hero_image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=600&fit=crop',
    hero_cta_text: 'Reserve a Table', hero_cta_url: '#',
    about_title: 'Our Story',
    about_text: 'For nearly four decades, La Maison has been the destination for those who appreciate the art of fine dining. Our ingredients are sourced daily from local farms and the finest importers across Europe.',
    about_image_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=600&h=400&fit=crop',
    features: [
      { title: 'Tasting Menu', icon: '🍽️', description: '7-course seasonal tasting experience — $120' },
      { title: 'Wine Cellar', icon: '🍷', description: '500+ labels from world-renowned vineyards' },
      { title: 'Private Events', icon: '🎉', description: 'Exclusive dining rooms for up to 40 guests' },
    ],
    testimonials: [
      { name: 'Michelin Guide', text: 'A masterful blend of French technique and Italian soul. Two stars.', role: 'Restaurant Review' },
      { name: 'David & Sarah', text: 'Our anniversary tradition for 10 years. Every visit feels like the first time.', role: 'Loyal Guests' },
    ],
    gallery: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&h=500&fit=crop', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=500&h=500&fit=crop', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=500&fit=crop'],
    cta_title: 'Make a Reservation',
    cta_subtitle: 'Open Tuesday–Sunday, 6 PM – 11 PM',
    cta_button_text: 'Book Now', cta_button_url: '#',
    phone: '+1 (555) 867-5309', email: 'reservations@lamaison.com', address: '42 Grand Avenue, New York, NY 10013', whatsapp: '+15558675309',
    website: null, linkedin: null, instagram: 'https://instagram.com', github: null, twitter: null, youtube: null, footer_text: null,
  },
  'fitness-trainer': {
    site_name: 'FitPro Academy',
    tagline: 'Transform Your Body, Transform Your Life',
    logo_url: null, favicon_url: null,
    hero_title: 'Get the Body You\'ve Always Wanted',
    hero_subtitle: 'Personalized training programs, nutrition plans, and 24/7 support from certified trainers.',
    hero_image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=600&fit=crop',
    hero_cta_text: 'Start Your Journey', hero_cta_url: '#',
    about_title: 'Meet Your Coach',
    about_text: 'Hi, I\'m Mike Torres — NASM certified trainer with 12 years of experience helping 500+ clients achieve their fitness goals. Whether you want to lose weight, build muscle, or boost energy, I\'ve got your back.',
    about_image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&h=500&fit=crop',
    features: [
      { title: 'Personal Training', icon: '💪', description: '1-on-1 sessions tailored to your goals' },
      { title: 'Nutrition Plans', icon: '🥗', description: 'Custom meal plans that fit your lifestyle' },
      { title: 'Online Coaching', icon: '📱', description: 'Train anywhere with video guidance' },
      { title: 'Group Classes', icon: '🏋️', description: 'High-energy HIIT, yoga, and bootcamp' },
    ],
    testimonials: [
      { name: 'Rachel Kim', text: 'Lost 30 lbs in 4 months. Mike\'s program changed my life!', role: 'Client' },
      { name: 'Tom Bradley', text: 'Best trainer I\'ve ever worked with. Results speak for themselves.', role: 'Client' },
    ],
    gallery: [],
    cta_title: 'Your Transformation Starts Today',
    cta_subtitle: 'First session is FREE. No commitment required.',
    cta_button_text: 'Book Free Session', cta_button_url: '#',
    phone: '+1 (555) 234-5678', email: 'mike@fitpro.com', address: '100 Fitness Blvd, Los Angeles, CA', whatsapp: '+15552345678',
    website: null, linkedin: null, instagram: 'https://instagram.com', github: null, twitter: null, youtube: 'https://youtube.com', footer_text: null,
  },
  'real-estate': {
    site_name: 'Prime Properties',
    tagline: 'Your Dream Home Awaits',
    logo_url: null, favicon_url: null,
    hero_title: 'Find Your Perfect Home',
    hero_subtitle: 'Luxury residences, commercial spaces, and investment properties in prime locations.',
    hero_image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=600&fit=crop',
    hero_cta_text: 'View Listings', hero_cta_url: '#',
    about_title: 'Why Choose Us?',
    about_text: 'With 20+ years in real estate, Prime Properties has helped 2,000+ families find their dream home. Our agents provide personalized service from first visit to closing day.',
    about_image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop',
    features: [
      { title: 'Luxury Homes', icon: '🏡', description: 'Premium properties in top neighborhoods' },
      { title: 'Commercial', icon: '🏢', description: 'Office spaces and retail locations' },
      { title: 'Investment', icon: '📈', description: 'High-ROI rental and flip opportunities' },
    ],
    testimonials: [{ name: 'The Johnsons', text: 'Found our dream home in just 2 weeks. Amazing service!', role: 'Homeowners' }],
    gallery: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=500&fit=crop', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=500&h=500&fit=crop'],
    cta_title: 'Schedule a Free Consultation',
    cta_subtitle: 'Let our experts find your perfect property.',
    cta_button_text: 'Contact Agent', cta_button_url: '#',
    phone: '+1 (555) 345-6789', email: 'info@primeproperties.com', address: '500 Realtor Drive, Miami, FL', whatsapp: '+15553456789',
    website: null, linkedin: 'https://linkedin.com', instagram: 'https://instagram.com', github: null, twitter: null, youtube: null, footer_text: null,
  },
  'doctor-clinic': {
    site_name: 'Dr. Priya Sharma',
    tagline: 'Compassionate Care, Modern Medicine',
    logo_url: null, favicon_url: null,
    hero_title: 'Your Health, Our Priority',
    hero_subtitle: 'Board-certified family physician providing comprehensive healthcare for all ages. Now accepting new patients.',
    hero_image_url: null,
    hero_cta_text: 'Book Appointment', hero_cta_url: '#',
    about_title: 'About Dr. Sharma',
    about_text: 'Dr. Priya Sharma is a Harvard-trained family physician with 15 years of experience. She specializes in preventive care, chronic disease management, and pediatric health.',
    about_image_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&h=500&fit=crop',
    features: [
      { title: 'General Checkups', icon: '🩺', description: 'Comprehensive annual health exams' },
      { title: 'Telemedicine', icon: '📱', description: 'Virtual consultations from home' },
      { title: 'Lab & Diagnostics', icon: '🧪', description: 'On-site blood work and imaging' },
      { title: 'Pediatrics', icon: '👶', description: 'Newborn to teen healthcare' },
    ],
    testimonials: [
      { name: 'Anita Patel', text: 'Dr. Sharma is the most caring doctor we\'ve ever had. Our whole family goes to her.', role: 'Patient' },
    ],
    gallery: [],
    cta_title: 'Book Your Appointment Today',
    cta_subtitle: 'Same-day appointments available. Most insurance accepted.',
    cta_button_text: 'Schedule Now', cta_button_url: '#',
    phone: '+1 (555) 456-7890', email: 'clinic@drsharma.com', address: '200 Health Center Dr, Suite 300', whatsapp: '+15554567890',
    website: null, linkedin: null, instagram: null, github: null, twitter: null, youtube: null, footer_text: null,
  },
  'education-course': {
    site_name: 'SkillMaster',
    tagline: 'Learn Skills That Matter',
    logo_url: null, favicon_url: null,
    hero_title: 'Master Any Skill in 30 Days',
    hero_subtitle: 'Expert-led courses in design, coding, business, and more. Learn at your own pace with hands-on projects.',
    hero_image_url: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=500&fit=crop',
    hero_cta_text: 'Browse Courses', hero_cta_url: '#',
    about_title: 'Why SkillMaster?',
    about_text: '50,000+ students trust SkillMaster for career-boosting skills. Our project-based learning ensures you don\'t just learn — you build a portfolio that gets you hired.',
    about_image_url: null,
    features: [
      { title: 'Expert Instructors', icon: '👨‍🏫', description: 'Learn from industry professionals' },
      { title: 'Lifetime Access', icon: '♾️', description: 'Buy once, learn forever' },
      { title: 'Certificates', icon: '🏆', description: 'Earn verified completion certificates' },
    ],
    testimonials: [
      { name: 'Ravi Kumar', text: 'Got hired as a developer 2 months after completing the full-stack course!', role: 'Student' },
    ],
    gallery: [], cta_title: 'Start Learning Today', cta_subtitle: '7-day free trial. Cancel anytime.',
    cta_button_text: 'Enroll Now', cta_button_url: '#',
    phone: null, email: 'support@skillmaster.com', address: null, whatsapp: null,
    website: null, linkedin: 'https://linkedin.com', instagram: 'https://instagram.com', github: null, twitter: 'https://twitter.com', youtube: 'https://youtube.com', footer_text: null,
  },
  'ngo-charity': {
    site_name: 'Hope Foundation',
    tagline: 'Building a Better Tomorrow',
    logo_url: null, favicon_url: null,
    hero_title: 'Every Child Deserves a Chance',
    hero_subtitle: 'We provide education, healthcare, and shelter to underprivileged children across 15 countries.',
    hero_image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&h=600&fit=crop',
    hero_cta_text: 'Donate Now', hero_cta_url: '#',
    about_title: 'Our Mission',
    about_text: 'Since 2005, Hope Foundation has impacted 100,000+ lives. We believe every child deserves access to quality education, nutrition, and a safe home. 92% of donations go directly to programs.',
    about_image_url: 'https://images.unsplash.com/photo-1509099836639-18ba4637571d?w=600&h=400&fit=crop',
    features: [
      { title: 'Education', icon: '📚', description: '50+ schools built across rural communities' },
      { title: 'Healthcare', icon: '🏥', description: 'Free medical camps serving 20,000+ annually' },
      { title: 'Clean Water', icon: '💧', description: '200+ wells providing safe drinking water' },
    ],
    testimonials: [
      { name: 'UNICEF', text: 'Hope Foundation is a model for grassroots impact in developing nations.', role: 'Partner Organization' },
    ],
    gallery: [], cta_title: 'Make a Difference Today', cta_subtitle: 'Your $25 provides a month of meals for a child.',
    cta_button_text: 'Donate Now', cta_button_url: '#',
    phone: '+1 (555) 567-8901', email: 'donate@hopefoundation.org', address: 'New York, NY', whatsapp: null,
    website: null, linkedin: 'https://linkedin.com', instagram: 'https://instagram.com', github: null, twitter: 'https://twitter.com', youtube: 'https://youtube.com', footer_text: null,
  },
  'ai-product': {
    site_name: 'NeuralAI',
    tagline: 'Intelligence, Automated',
    logo_url: null, favicon_url: null,
    hero_title: 'AI That Actually Understands Your Business',
    hero_subtitle: 'Automate workflows, generate insights, and make smarter decisions with our enterprise AI platform.',
    hero_image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop',
    hero_cta_text: 'Request Demo', hero_cta_url: '#',
    about_title: 'The Future of Work',
    about_text: 'NeuralAI combines large language models with your business data to create AI agents that handle tasks, answer questions, and generate reports — all while learning and improving.',
    about_image_url: null,
    features: [
      { title: 'AI Agents', icon: '🤖', description: 'Autonomous agents that complete complex tasks' },
      { title: 'Knowledge Base', icon: '🧠', description: 'Train on your docs, data, and processes' },
      { title: 'Integrations', icon: '🔗', description: 'Connect with Slack, Jira, Salesforce, and 200+ tools' },
      { title: 'Enterprise Security', icon: '🛡️', description: 'SOC2, HIPAA, GDPR compliant' },
    ],
    testimonials: [
      { name: 'VP Operations, Deloitte', text: 'NeuralAI cut our report generation time from 3 days to 3 minutes.', role: 'Enterprise Client' },
      { name: 'CTO, Acme Corp', text: 'The ROI was visible within the first month. Game-changing technology.', role: 'Enterprise Client' },
    ],
    gallery: [], cta_title: 'See AI in Action', cta_subtitle: 'Book a personalized demo with our solutions team.',
    cta_button_text: 'Schedule Demo', cta_button_url: '#',
    phone: null, email: 'sales@neural-ai.com', address: 'San Francisco, CA', whatsapp: null,
    website: null, linkedin: 'https://linkedin.com', instagram: null, github: 'https://github.com', twitter: 'https://twitter.com', youtube: null, footer_text: null,
  },
  'wedding-invite': {
    site_name: 'Priya & Arjun',
    tagline: 'We\'re Getting Married!',
    logo_url: null, favicon_url: null,
    hero_title: 'Priya & Arjun',
    hero_subtitle: 'Join us as we celebrate our love. Saturday, December 14, 2026 at The Grand Ballroom, Mumbai.',
    hero_image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=600&fit=crop',
    hero_cta_text: 'RSVP Now', hero_cta_url: '#',
    about_title: 'Our Love Story',
    about_text: 'We met at a coffee shop in 2020, bonded over bad jokes and great chai. Three years, two dogs, and countless adventures later, we\'re ready to say "I do."',
    about_image_url: 'https://images.unsplash.com/photo-1529636798458-92182e662485?w=600&h=400&fit=crop',
    features: [
      { title: 'Ceremony', icon: '💍', description: '4:00 PM — The Grand Ballroom, Main Hall' },
      { title: 'Reception', icon: '🥂', description: '7:00 PM — Rooftop Garden & Dinner' },
      { title: 'After Party', icon: '🎶', description: '10:00 PM — DJ & Dancing till midnight' },
    ],
    testimonials: [], gallery: [
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=500&h=500&fit=crop',
    ],
    cta_title: 'Will You Join Us?', cta_subtitle: 'Please RSVP by November 1, 2026',
    cta_button_text: 'RSVP Here', cta_button_url: '#',
    phone: '+91 98765 43210', email: 'priyaarjun2026@gmail.com', address: 'The Grand Ballroom, Bandra West, Mumbai', whatsapp: '+919876543210',
    website: null, linkedin: null, instagram: 'https://instagram.com', github: null, twitter: null, youtube: null, footer_text: 'With love, Priya & Arjun 💕',
  },
  'music-artist': {
    site_name: 'DJ Nova',
    tagline: 'Electronic Music Producer & DJ',
    logo_url: null, favicon_url: null,
    hero_title: 'Feel the Rhythm',
    hero_subtitle: 'International DJ & Producer. 50M+ streams. Bringing the beat to stages worldwide.',
    hero_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=600&fit=crop',
    hero_cta_text: 'Listen Now', hero_cta_url: '#',
    about_title: 'About Nova',
    about_text: 'From underground raves to Tomorrowland main stage — Nova\'s journey through electronic music spans 8 years and 4 continents. His signature blend of progressive house and melodic techno has earned him a global fanbase.',
    about_image_url: null,
    features: [
      { title: 'Latest Album', icon: '💿', description: '"Neon Dreams" — Out Now on all platforms' },
      { title: 'World Tour 2026', icon: '🌍', description: '30 cities across Europe, Asia & Americas' },
      { title: 'Booking', icon: '🎧', description: 'Available for festivals, clubs & private events' },
    ],
    testimonials: [{ name: 'Billboard', text: 'Nova is the future of electronic music. A must-see live act.', role: 'Music Review' }],
    gallery: [], cta_title: 'Book Nova for Your Event', cta_subtitle: null,
    cta_button_text: 'Get in Touch', cta_button_url: '#',
    phone: null, email: 'booking@djnova.com', address: null, whatsapp: null,
    website: null, linkedin: null, instagram: 'https://instagram.com', github: null, twitter: 'https://twitter.com', youtube: 'https://youtube.com', footer_text: null,
  },
};

/**
 * Get preset content for a template. Falls back to gradient-startup if no preset exists.
 */
export function getPresetForTemplate(templateId: string): PresetContent {
  return presets[templateId] || presets['gradient-startup'];
}

/** List of template IDs that have rich presets */
export const PRESET_TEMPLATE_IDS = Object.keys(presets);
